#!/usr/bin/env python3
"""
Parametric FreeCAD 3D CAD & STEP Solid Builder for Plan 5: 1 BHK Solar Chamfer Villa (495 sq.ft)
Auto-generated by ThermaBuild BIM Engine.
"""

import sys
import os

try:
    import FreeCAD as App
    import Part
except ImportError:
    print("FreeCAD Python API not found. To build solid STEP CAD model:")
    print("Run: FreeCADCmd generate_cad.py")
    sys.exit(0)

doc = App.newDocument("ThermaBuild_plan_5")

# 1. Foundation Slab (Reinforced Concrete Plinth)
slab = Part.makeBox(8750.0, 7610.0, 150)
slab.translate(App.Vector(-300, -300, 0))
slab_obj = doc.addObject("Part::Feature", "Foundation_Slab")
slab_obj.Shape = slab

# 2. Roof Slab (High-Thermal Insulation Overdeck)
roof = Part.makeBox(8950.0, 7810.0, 150)
roof.translate(App.Vector(-400, -400, 2900.0))
roof_obj = doc.addObject("Part::Feature", "Roof_Slab")
roof_obj.Shape = roof

# 3. Exterior Envelope Perimeter Walls
w_s = Part.makeBox(8150.0, 200.0, 2750.0)
w_s.translate(App.Vector(0, 0, 150))
doc.addObject("Part::Feature", "Wall_South").Shape = w_s

w_n = Part.makeBox(8150.0, 200.0, 2750.0)
w_n.translate(App.Vector(0, 6810.0, 150))
doc.addObject("Part::Feature", "Wall_North").Shape = w_n

w_w = Part.makeBox(200.0, 6610.0, 2750.0)
w_w.translate(App.Vector(0, 200.0, 150))
doc.addObject("Part::Feature", "Wall_West").Shape = w_w

w_e = Part.makeBox(200.0, 6610.0, 2750.0)
w_e.translate(App.Vector(7950.0, 200.0, 150))
doc.addObject("Part::Feature", "Wall_East").Shape = w_e

# 4. Interior Room Zones & Partitions

# Room 1: Daylit Living Room (4.6m x 3.6m)
r_box = Part.makeBox(4600.0, 3600.0, 30)
r_box.translate(App.Vector(200.0, 200.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_1_Daylit_Living_Room")
r_obj.Shape = r_box

# Room 2: Entrance Foyer (3m x 1.8m)
r_box = Part.makeBox(3000.0, 1800.0, 30)
r_box.translate(App.Vector(4900.0, 200.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_2_Entrance_Foyer")
r_obj.Shape = r_box

# Room 3: Master Bedroom (4.2m x 2.9m)
r_box = Part.makeBox(4200.0, 2900.0, 30)
r_box.translate(App.Vector(200.0, 3900.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_3_Master_Bedroom")
r_obj.Shape = r_box

# Room 4: Gourmet Kitchen (3m x 2.6m)
r_box = Part.makeBox(3000.0, 2600.0, 30)
r_box.translate(App.Vector(4900.0, 2100.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_4_Gourmet_Kitchen")
r_obj.Shape = r_box

# Room 5: Full Bathroom (3m x 2m)
r_box = Part.makeBox(3000.0, 2000.0, 30)
r_box.translate(App.Vector(4900.0, 4800.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_5_Full_Bathroom")
r_obj.Shape = r_box


doc.recompute()
step_path = os.path.join(os.path.dirname(__file__), "house.step")
Part.export([slab_obj, roof_obj], step_path)
print(f"Exported parametric solid CAD STEP: {step_path}")

fcstd_path = os.path.join(os.path.dirname(__file__), "house.FCStd")
doc.saveAs(fcstd_path)
print(f"Saved native FreeCAD project: {fcstd_path}")
