#!/usr/bin/env python3
"""
Parametric FreeCAD 3D CAD & STEP Solid Builder for Plan 2: 4 BHK Suburban Residence (960 sq.ft)
Auto-generated by ThermaBuild BIM Engine.
"""

import sys
import os

try:
    import FreeCAD as App
    import Part
except ImportError:
    print("FreeCAD Python API not found. To build solid STEP CAD model:")
    print("Run: FreeCADCmd generate_cad.py")
    sys.exit(0)

doc = App.newDocument("ThermaBuild_plan_2")

# 1. Foundation Slab (Reinforced Concrete Plinth)
slab = Part.makeBox(8600.0, 10100.0, 150)
slab.translate(App.Vector(-300, -300, 0))
slab_obj = doc.addObject("Part::Feature", "Foundation_Slab")
slab_obj.Shape = slab

# 2. Roof Slab (High-Thermal Insulation Overdeck)
roof = Part.makeBox(8800.0, 10300.0, 150)
roof.translate(App.Vector(-400, -400, 3000.0))
roof_obj = doc.addObject("Part::Feature", "Roof_Slab")
roof_obj.Shape = roof

# 3. Exterior Envelope Perimeter Walls
w_s = Part.makeBox(8000.0, 200.0, 2850.0)
w_s.translate(App.Vector(0, 0, 150))
doc.addObject("Part::Feature", "Wall_South").Shape = w_s

w_n = Part.makeBox(8000.0, 200.0, 2850.0)
w_n.translate(App.Vector(0, 9300.0, 150))
doc.addObject("Part::Feature", "Wall_North").Shape = w_n

w_w = Part.makeBox(200.0, 9100.0, 2850.0)
w_w.translate(App.Vector(0, 200.0, 150))
doc.addObject("Part::Feature", "Wall_West").Shape = w_w

w_e = Part.makeBox(200.0, 9100.0, 2850.0)
w_e.translate(App.Vector(7800.0, 200.0, 150))
doc.addObject("Part::Feature", "Wall_East").Shape = w_e

# 4. Interior Room Zones & Partitions

# Room 1: Front Porch (4.12m x 2m)
r_box = Part.makeBox(4120.0, 2000.0, 30)
r_box.translate(App.Vector(200.0, 200.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_1_Front_Porch")
r_obj.Shape = r_box

# Room 2: Living Room (4m x 2.7m)
r_box = Part.makeBox(4000.0, 2700.0, 30)
r_box.translate(App.Vector(200.0, 2300.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_2_Living_Room")
r_obj.Shape = r_box

# Room 3: Dining Room (4m x 2m)
r_box = Part.makeBox(4000.0, 2000.0, 30)
r_box.translate(App.Vector(200.0, 5100.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_3_Dining_Room")
r_obj.Shape = r_box

# Room 4: Kitchen (3.5m x 2m)
r_box = Part.makeBox(3500.0, 2000.0, 30)
r_box.translate(App.Vector(4300.0, 5100.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_4_Kitchen")
r_obj.Shape = r_box

# Room 5: Master Bedroom (3.8m x 2.1m)
r_box = Part.makeBox(3800.0, 2100.0, 30)
r_box.translate(App.Vector(200.0, 7200.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_5_Master_Bedroom")
r_obj.Shape = r_box

# Room 6: Bedroom 4 (3.7m x 2.1m)
r_box = Part.makeBox(3700.0, 2100.0, 30)
r_box.translate(App.Vector(4100.0, 7200.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_6_Bedroom_4")
r_obj.Shape = r_box

# Room 7: Bedroom 1 (3.4m x 2.35m)
r_box = Part.makeBox(3400.0, 2350.0, 30)
r_box.translate(App.Vector(4400.0, 200.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_7_Bedroom_1")
r_obj.Shape = r_box

# Room 8: Bedroom 2 (3.4m x 2.35m)
r_box = Part.makeBox(3400.0, 2350.0, 30)
r_box.translate(App.Vector(4400.0, 2650.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_8_Bedroom_2")
r_obj.Shape = r_box

# Room 9: Common Bath (1m x 1.8m)
r_box = Part.makeBox(1000.0, 1800.0, 30)
r_box.translate(App.Vector(3200.0, 4800.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_9_Common_Bath")
r_obj.Shape = r_box


doc.recompute()
step_path = os.path.join(os.path.dirname(__file__), "house.step")
Part.export([slab_obj, roof_obj], step_path)
print(f"Exported parametric solid CAD STEP: {step_path}")

fcstd_path = os.path.join(os.path.dirname(__file__), "house.FCStd")
doc.saveAs(fcstd_path)
print(f"Saved native FreeCAD project: {fcstd_path}")
