// Auto-generated by ThermaBuild
window.CAD_PROJECTS = {
  "catalog": {
    "sofa": {
      "size": [
        2.2,
        0.95,
        0.82
      ],
      "color": [
        0.45,
        0.35,
        0.28,
        1
      ],
      "roughness": 0.85
    },
    "coffee_table": {
      "size": [
        1.1,
        0.6,
        0.42
      ],
      "color": [
        0.35,
        0.22,
        0.12,
        1
      ],
      "roughness": 0.4
    },
    "tv_unit": {
      "size": [
        1.8,
        0.45,
        0.55
      ],
      "color": [
        0.15,
        0.12,
        0.1,
        1
      ],
      "roughness": 0.5
    },
    "floor_lamp": {
      "size": [
        0.35,
        0.35,
        1.65
      ],
      "color": [
        0.85,
        0.75,
        0.35,
        1
      ],
      "roughness": 0.3,
      "emission": 0.8
    },
    "plant": {
      "size": [
        0.45,
        0.45,
        1.1
      ],
      "color": [
        0.2,
        0.55,
        0.25,
        1
      ],
      "roughness": 0.9
    },
    "pooja_mandir": {
      "size": [
        1,
        0.45,
        1.8
      ],
      "color": [
        0.72,
        0.52,
        0.18,
        1
      ],
      "roughness": 0.35,
      "emission": 0.15
    },
    "kitchen_counter": {
      "size": [
        2.4,
        0.62,
        0.9
      ],
      "color": [
        0.75,
        0.75,
        0.73,
        1
      ],
      "roughness": 0.25
    },
    "stove": {
      "size": [
        0.6,
        0.55,
        0.05
      ],
      "color": [
        0.2,
        0.2,
        0.2,
        1
      ],
      "roughness": 0.2
    },
    "fridge": {
      "size": [
        0.7,
        0.65,
        1.75
      ],
      "color": [
        0.92,
        0.92,
        0.94,
        1
      ],
      "roughness": 0.15
    },
    "dining_table": {
      "size": [
        1.2,
        0.75,
        0.75
      ],
      "color": [
        0.4,
        0.28,
        0.18,
        1
      ],
      "roughness": 0.45
    },
    "dining_chair": {
      "size": [
        0.45,
        0.45,
        0.9
      ],
      "color": [
        0.5,
        0.38,
        0.28,
        1
      ],
      "roughness": 0.7
    },
    "bed_double": {
      "size": [
        2,
        1.6,
        0.55
      ],
      "color": [
        0.55,
        0.48,
        0.62,
        1
      ],
      "roughness": 0.9
    },
    "bed_single": {
      "size": [
        1,
        1.9,
        0.5
      ],
      "color": [
        0.48,
        0.58,
        0.72,
        1
      ],
      "roughness": 0.9
    },
    "wardrobe": {
      "size": [
        0.6,
        1.8,
        2.2
      ],
      "color": [
        0.32,
        0.24,
        0.18,
        1
      ],
      "roughness": 0.5
    },
    "side_table": {
      "size": [
        0.5,
        0.4,
        0.55
      ],
      "color": [
        0.38,
        0.28,
        0.18,
        1
      ],
      "roughness": 0.45
    },
    "study_desk": {
      "size": [
        1.2,
        0.6,
        0.75
      ],
      "color": [
        0.42,
        0.32,
        0.22,
        1
      ],
      "roughness": 0.4
    },
    "office_chair": {
      "size": [
        0.55,
        0.55,
        1
      ],
      "color": [
        0.18,
        0.18,
        0.22,
        1
      ],
      "roughness": 0.6
    },
    "bookshelf": {
      "size": [
        0.35,
        1,
        1.8
      ],
      "color": [
        0.35,
        0.25,
        0.15,
        1
      ],
      "roughness": 0.55
    },
    "toy_chest": {
      "size": [
        0.8,
        0.5,
        0.45
      ],
      "color": [
        0.85,
        0.55,
        0.25,
        1
      ],
      "roughness": 0.7
    },
    "toilet": {
      "size": [
        0.4,
        0.65,
        0.75
      ],
      "color": [
        0.95,
        0.95,
        0.97,
        1
      ],
      "roughness": 0.1
    },
    "sink": {
      "size": [
        0.55,
        0.45,
        0.85
      ],
      "color": [
        0.9,
        0.9,
        0.92,
        1
      ],
      "roughness": 0.1
    },
    "shoe_rack": {
      "size": [
        1,
        0.35,
        0.9
      ],
      "color": [
        0.3,
        0.22,
        0.15,
        1
      ],
      "roughness": 0.5
    },
    "console_table": {
      "size": [
        1.2,
        0.4,
        0.85
      ],
      "color": [
        0.38,
        0.28,
        0.18,
        1
      ],
      "roughness": 0.4
    },
    "ceiling_light": {
      "size": [
        0.42,
        0.42,
        0.08
      ],
      "color": [
        0.98,
        0.96,
        0.92,
        1
      ],
      "roughness": 0.15,
      "emission": 0.8
    },
    "ceiling_fan": {
      "size": [
        1.2,
        1.2,
        0.35
      ],
      "color": [
        0.75,
        0.75,
        0.78,
        1
      ],
      "roughness": 0.35,
      "metalness": 0.6
    },
    "pendant_light": {
      "size": [
        0.28,
        0.28,
        0.55
      ],
      "color": [
        0.95,
        0.93,
        0.88,
        1
      ],
      "roughness": 0.2,
      "emission": 1.2
    }
  },
  "projects": [
    {
      "id": "test-vastu",
      "property": {
        "id": "test-vastu",
        "name": "Vastu 3BHK Test",
        "facing": "E",
        "dimensions_m": {
          "width": 9.44,
          "depth": 11.8
        },
        "area_sqft": 1199,
        "area_m2": 111.4,
        "bhk": 3,
        "apply_vastu": true,
        "rooms": [
          {
            "name": "Living & Dining",
            "direction": "NE",
            "vastu_item": "Living & Dining"
          },
          {
            "name": "Kitchen",
            "direction": "SE",
            "vastu_item": "Kitchen"
          },
          {
            "name": "Master Bedroom",
            "direction": "SW",
            "vastu_item": "Master Bedroom"
          },
          {
            "name": "Bedroom 2",
            "direction": "NW",
            "vastu_item": "Bedroom 2"
          },
          {
            "name": "Bathroom",
            "direction": "W",
            "vastu_item": "Bathroom"
          }
        ]
      },
      "layout": {
        "wall_height_m": 2.85,
        "wall_thickness_m": 0.23,
        "style": "modern_passive",
        "rooms": [
          {
            "name": "Living & Dining",
            "rect": {
              "x": 0.2,
              "y": 0.2,
              "w": 4.68,
              "h": 5.5
            },
            "floor": "oak_parquet",
            "wall_color": [
              0.96,
              0.95,
              0.92,
              1
            ],
            "furniture": [
              {
                "type": "sofa",
                "x": 2.11,
                "y": 3.58,
                "rotation_deg": 0
              },
              {
                "type": "coffee_table",
                "x": 2.11,
                "y": 2.48,
                "rotation_deg": 0
              },
              {
                "type": "tv_unit",
                "x": 2.11,
                "y": 0.5,
                "rotation_deg": 0
              },
              {
                "type": "dining_table",
                "x": 3.74,
                "y": 2.75,
                "rotation_deg": 0
              },
              {
                "type": "ceiling_fan",
                "x": 2.11,
                "y": 2.75,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "N",
                "offset": 1.5,
                "width": 2.2,
                "height": 1.4,
                "sill_m": 0.9
              }
            ],
            "zone": "NE"
          },
          {
            "name": "Kitchen",
            "rect": {
              "x": 4.88,
              "y": 0.2,
              "w": 3.96,
              "h": 5.5
            },
            "floor": "ceramic_tile",
            "wall_color": [
              0.93,
              0.93,
              0.91,
              1
            ],
            "furniture": [
              {
                "type": "kitchen_counter",
                "x": 8.34,
                "y": 1.2,
                "rotation_deg": 90
              },
              {
                "type": "fridge",
                "x": 5.48,
                "y": 0.6,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "E",
                "offset": 1.2,
                "width": 1.4,
                "height": 1.2,
                "sill_m": 1.0
              }
            ],
            "zone": "SE"
          },
          {
            "name": "Master Bedroom",
            "rect": {
              "x": 0.2,
              "y": 5.9,
              "w": 4.68,
              "h": 5.3
            },
            "floor": "hardwood",
            "wall_color": [
              0.95,
              0.94,
              0.91,
              1
            ],
            "furniture": [
              {
                "type": "bed_double",
                "x": 2.11,
                "y": 8.82,
                "rotation_deg": 0
              },
              {
                "type": "wardrobe",
                "x": 0.6,
                "y": 7.75,
                "rotation_deg": 90
              },
              {
                "type": "ceiling_fan",
                "x": 2.11,
                "y": 8.55,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "S",
                "offset": 1.2,
                "width": 1.8,
                "height": 1.4,
                "sill_m": 0.9
              }
            ],
            "zone": "SW"
          },
          {
            "name": "Bedroom 2",
            "rect": {
              "x": 4.88,
              "y": 5.9,
              "w": 3.96,
              "h": 3.44
            },
            "floor": "hardwood",
            "wall_color": [
              0.94,
              0.95,
              0.93,
              1
            ],
            "furniture": [
              {
                "type": "bed_single",
                "x": 6.86,
                "y": 7.62,
                "rotation_deg": 0
              },
              {
                "type": "study_desk",
                "x": 5.48,
                "y": 6.5,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "W",
                "offset": 1.0,
                "width": 1.5,
                "height": 1.4,
                "sill_m": 0.9
              }
            ],
            "zone": "NW"
          },
          {
            "name": "Bathroom",
            "rect": {
              "x": 4.88,
              "y": 9.54,
              "w": 3.96,
              "h": 1.66
            },
            "floor": "slate_gray",
            "wall_color": [
              0.91,
              0.91,
              0.91,
              1
            ],
            "furniture": [
              {
                "type": "toilet",
                "x": 6.86,
                "y": 10.04,
                "rotation_deg": 0
              },
              {
                "type": "sink",
                "x": 6.86,
                "y": 10.7,
                "rotation_deg": 180
              }
            ],
            "windows": [
              {
                "wall": "W",
                "offset": 0.6,
                "width": 0.6,
                "height": 0.6,
                "sill_m": 1.8
              }
            ],
            "zone": "W"
          }
        ],
        "doors": [
          {
            "from": "Living & Dining",
            "to": "Kitchen",
            "x": 4.88,
            "y": 1.2,
            "width": 0.9
          },
          {
            "from": "Living & Dining",
            "to": "Master Bedroom",
            "x": 2.34,
            "y": 5.9,
            "width": 0.9
          },
          {
            "from": "Living & Dining",
            "to": "Bedroom 2",
            "x": 4.88,
            "y": 6.7,
            "width": 0.85
          },
          {
            "from": "Living & Dining",
            "to": "Bathroom",
            "x": 4.88,
            "y": 10.04,
            "width": 0.8
          }
        ]
      },
      "vastu": {
        "compliance_score": 66,
        "grade": "Needs improvement",
        "rooms": [
          {
            "name": "Living & Dining",
            "vastu_item": "Living & Dining",
            "direction": "NE",
            "status": "unknown",
            "score": 50,
            "note": "No specific rule \u2014 verify manually"
          },
          {
            "name": "Kitchen",
            "vastu_item": "Kitchen",
            "direction": "SE",
            "status": "good",
            "score": 80,
            "note": "Acceptable placement"
          },
          {
            "name": "Master Bedroom",
            "vastu_item": "Master Bedroom",
            "direction": "SW",
            "status": "best",
            "score": 100,
            "note": "Ideal placement per classical Vastu"
          },
          {
            "name": "Bedroom 2",
            "vastu_item": "Bedroom 2",
            "direction": "NW",
            "status": "unknown",
            "score": 50,
            "note": "No specific rule \u2014 verify manually"
          },
          {
            "name": "Bathroom",
            "vastu_item": "Bathroom",
            "direction": "W",
            "status": "unknown",
            "score": 50,
            "note": "No specific rule \u2014 verify manually"
          }
        ],
        "issues": []
      },
      "astro": {},
      "assets": {
        "hero": "../output/test-vastu/floor-plan.svg",
        "floorPlan": "../output/test-vastu/floor-plan.svg"
      }
    },
    {
      "id": "test-functional",
      "property": {
        "id": "test-functional",
        "name": "Functional 2BHK Test",
        "facing": "E",
        "dimensions_m": {
          "width": 7.71,
          "depth": 9.64
        },
        "area_sqft": 800,
        "area_m2": 74.3,
        "bhk": 2,
        "apply_vastu": false,
        "rooms": [
          {
            "name": "Living & Dining",
            "direction": "Frontage",
            "vastu_item": "Living & Dining"
          },
          {
            "name": "Kitchen",
            "direction": "Service",
            "vastu_item": "Kitchen"
          },
          {
            "name": "Master Bedroom",
            "direction": "Private",
            "vastu_item": "Master Bedroom"
          },
          {
            "name": "Bedroom 2",
            "direction": "Private",
            "vastu_item": "Bedroom 2"
          },
          {
            "name": "Bathroom",
            "direction": "Wet",
            "vastu_item": "Bathroom"
          }
        ]
      },
      "layout": {
        "wall_height_m": 2.85,
        "wall_thickness_m": 0.23,
        "style": "modern_passive",
        "rooms": [
          {
            "name": "Living & Dining",
            "rect": {
              "x": 0.2,
              "y": 0.2,
              "w": 4.09,
              "h": 4.44
            },
            "floor": "oak_parquet",
            "wall_color": [
              0.96,
              0.95,
              0.93,
              1
            ],
            "furniture": [
              {
                "type": "sofa",
                "x": 1.64,
                "y": 3.11,
                "rotation_deg": 0
              },
              {
                "type": "coffee_table",
                "x": 1.64,
                "y": 2.22,
                "rotation_deg": 0
              },
              {
                "type": "tv_unit",
                "x": 1.64,
                "y": 0.5,
                "rotation_deg": 0
              },
              {
                "type": "dining_table",
                "x": 3.27,
                "y": 2.0,
                "rotation_deg": 0
              },
              {
                "type": "ceiling_fan",
                "x": 2.04,
                "y": 2.22,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "E",
                "offset": 1.2,
                "width": 2.2,
                "height": 1.4,
                "sill_m": 0.9
              }
            ],
            "zone": "Frontage"
          },
          {
            "name": "Kitchen",
            "rect": {
              "x": 4.29,
              "y": 0.2,
              "w": 3.02,
              "h": 3.7
            },
            "floor": "ceramic_tile",
            "wall_color": [
              0.94,
              0.94,
              0.92,
              1
            ],
            "furniture": [
              {
                "type": "kitchen_counter",
                "x": 6.71,
                "y": 1.2,
                "rotation_deg": 90
              },
              {
                "type": "fridge",
                "x": 4.69,
                "y": 0.6,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "N",
                "offset": 1.0,
                "width": 1.2,
                "height": 1.2,
                "sill_m": 1.1
              }
            ],
            "zone": "Service"
          },
          {
            "name": "Master Bedroom",
            "rect": {
              "x": 0.2,
              "y": 4.74,
              "w": 4.09,
              "h": 4.3
            },
            "floor": "hardwood",
            "wall_color": [
              0.95,
              0.93,
              0.9,
              1
            ],
            "furniture": [
              {
                "type": "bed_double",
                "x": 1.84,
                "y": 7.11,
                "rotation_deg": 0
              },
              {
                "type": "wardrobe",
                "x": 0.6,
                "y": 6.03,
                "rotation_deg": 90
              },
              {
                "type": "ceiling_fan",
                "x": 1.84,
                "y": 6.89,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "S",
                "offset": 1.2,
                "width": 1.8,
                "height": 1.4,
                "sill_m": 0.9
              }
            ],
            "zone": "Private"
          },
          {
            "name": "Bedroom 2",
            "rect": {
              "x": 4.29,
              "y": 4.0,
              "w": 3.02,
              "h": 2.79
            },
            "floor": "hardwood",
            "wall_color": [
              0.94,
              0.95,
              0.92,
              1
            ],
            "furniture": [
              {
                "type": "bed_single",
                "x": 5.6,
                "y": 5.39,
                "rotation_deg": 0
              },
              {
                "type": "study_desk",
                "x": 4.69,
                "y": 4.6,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "E",
                "offset": 1.0,
                "width": 1.5,
                "height": 1.4,
                "sill_m": 0.9
              }
            ],
            "zone": "Private"
          },
          {
            "name": "Bathroom",
            "rect": {
              "x": 4.29,
              "y": 6.99,
              "w": 3.02,
              "h": 2.15
            },
            "floor": "slate_gray",
            "wall_color": [
              0.92,
              0.92,
              0.92,
              1
            ],
            "furniture": [
              {
                "type": "toilet",
                "x": 5.6,
                "y": 7.59,
                "rotation_deg": 0
              },
              {
                "type": "sink",
                "x": 5.6,
                "y": 8.64,
                "rotation_deg": 180
              }
            ],
            "windows": [
              {
                "wall": "E",
                "offset": 0.6,
                "width": 0.6,
                "height": 0.6,
                "sill_m": 1.8
              }
            ],
            "zone": "Wet"
          }
        ],
        "doors": [
          {
            "from": "Living & Dining",
            "to": "Kitchen",
            "x": 4.09,
            "y": 1.0,
            "width": 0.9
          },
          {
            "from": "Living & Dining",
            "to": "Master Bedroom",
            "x": 1.84,
            "y": 4.74,
            "width": 0.9
          },
          {
            "from": "Living & Dining",
            "to": "Bedroom 2",
            "x": 4.09,
            "y": 4.8,
            "width": 0.85
          },
          {
            "from": "Master Bedroom",
            "to": "Bathroom",
            "x": 4.09,
            "y": 7.59,
            "width": 0.8
          }
        ]
      },
      "vastu": {
        "compliance_score": 75,
        "grade": "Functional",
        "findings": [
          {
            "message": "Optimized for functional MEP adjacency and structural grid efficiency."
          }
        ]
      },
      "astro": {},
      "assets": {
        "hero": "../output/test-functional/floor-plan.svg",
        "floorPlan": "../output/test-functional/floor-plan.svg"
      }
    },
    {
      "id": "plan-1",
      "property": {
        "id": "plan-1",
        "name": "Plan 1: 2 BHK Compact Villa (1,158 sq.ft)",
        "description": "Dimensioned 2 BHK parametric model (10.26m \u00d7 10.49m). Optimal South/East solar aperture.",
        "facing": "S",
        "north_rotation_deg": 0,
        "dimensions_m": {
          "width": 10.26,
          "depth": 10.49
        },
        "area_sqft": 1158,
        "area_m2": 107.63,
        "bhk": 2,
        "rooms": [
          {
            "name": "Sit-Out & Foyer",
            "vastu_item": "Entrance",
            "direction": "SE"
          },
          {
            "name": "Living / Hall",
            "vastu_item": "Living & Dining",
            "direction": "NE"
          },
          {
            "name": "Dining Room",
            "vastu_item": "Dining Room",
            "direction": "North"
          },
          {
            "name": "Kitchen",
            "vastu_item": "Kitchen",
            "direction": "SE"
          },
          {
            "name": "Store Room",
            "vastu_item": "Storage",
            "direction": "East"
          },
          {
            "name": "Bedroom 1",
            "vastu_item": "Children/Guest Bedroom",
            "direction": "NW"
          },
          {
            "name": "Master Bedroom",
            "vastu_item": "Master Bedroom",
            "direction": "SW"
          },
          {
            "name": "Bath & WC",
            "vastu_item": "Toilet/Bath",
            "direction": "West"
          }
        ]
      },
      "layout": {
        "wall_height_m": 2.85,
        "wall_thickness_m": 0.2,
        "style": "compact_villa",
        "rooms": [
          {
            "name": "Sit-Out & Foyer",
            "rect": {
              "x": 3.4,
              "y": 0.2,
              "w": 3.12,
              "h": 1.38
            },
            "floor": "ceramic_tile",
            "furniture": [
              {
                "type": "shoe_rack",
                "x": 3.7,
                "y": 0.4,
                "rotation_deg": 0
              },
              {
                "type": "plant",
                "x": 6.2,
                "y": 0.4,
                "rotation_deg": 0
              }
            ],
            "windows": []
          },
          {
            "name": "Living / Hall",
            "rect": {
              "x": 2.2,
              "y": 1.7,
              "w": 5.28,
              "h": 3.72
            },
            "floor": "oak_parquet",
            "furniture": [
              {
                "type": "sofa",
                "x": 4.8,
                "y": 3.8,
                "rotation_deg": 0
              },
              {
                "type": "coffee_table",
                "x": 4.8,
                "y": 2.8,
                "rotation_deg": 0
              },
              {
                "type": "tv_unit",
                "x": 4.8,
                "y": 1.9,
                "rotation_deg": 0
              },
              {
                "type": "ceiling_fan",
                "x": 4.8,
                "y": 3.2,
                "rotation_deg": 0
              },
              {
                "type": "floor_lamp",
                "x": 2.6,
                "y": 4.8,
                "rotation_deg": 0
              },
              {
                "type": "plant",
                "x": 7,
                "y": 4.8,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "E",
                "offset": 1.2,
                "width": 1.5,
                "height": 1.3,
                "sill_m": 0.9
              }
            ]
          },
          {
            "name": "Dining Room",
            "rect": {
              "x": 3.4,
              "y": 5.5,
              "w": 3.12,
              "h": 4.44
            },
            "floor": "marble_white",
            "furniture": [
              {
                "type": "dining_table",
                "x": 4.9,
                "y": 7.6,
                "rotation_deg": 0
              },
              {
                "type": "pendant_light",
                "x": 4.9,
                "y": 7.6,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "N",
                "offset": 0.8,
                "width": 1.4,
                "height": 1.2,
                "sill_m": 0.9
              }
            ]
          },
          {
            "name": "Kitchen",
            "rect": {
              "x": 6.6,
              "y": 7.5,
              "w": 3.24,
              "h": 2.4
            },
            "floor": "ceramic_tile",
            "furniture": [
              {
                "type": "kitchen_counter",
                "x": 9.3,
                "y": 8.5,
                "rotation_deg": 90
              },
              {
                "type": "stove",
                "x": 9.3,
                "y": 9.3,
                "rotation_deg": 90
              },
              {
                "type": "fridge",
                "x": 6.9,
                "y": 9.4,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "N",
                "offset": 1.2,
                "width": 1.2,
                "height": 1.1,
                "sill_m": 1
              },
              {
                "wall": "E",
                "offset": 0.6,
                "width": 1,
                "height": 1,
                "sill_m": 1
              }
            ]
          },
          {
            "name": "Store Room",
            "rect": {
              "x": 7.6,
              "y": 5.5,
              "w": 1.2,
              "h": 1.8
            },
            "floor": "ceramic_tile",
            "furniture": [
              {
                "type": "bookshelf",
                "x": 8.2,
                "y": 6.9,
                "rotation_deg": 0
              }
            ],
            "windows": []
          },
          {
            "name": "Bedroom 1",
            "rect": {
              "x": 0.3,
              "y": 7,
              "w": 2.94,
              "h": 2.94
            },
            "floor": "oak_parquet",
            "furniture": [
              {
                "type": "bed_double",
                "x": 1.7,
                "y": 8.5,
                "rotation_deg": 0
              },
              {
                "type": "side_table",
                "x": 0.6,
                "y": 9.4,
                "rotation_deg": 0
              },
              {
                "type": "side_table",
                "x": 2.8,
                "y": 9.4,
                "rotation_deg": 0
              },
              {
                "type": "wardrobe",
                "x": 0.6,
                "y": 7.6,
                "rotation_deg": 90
              },
              {
                "type": "ceiling_fan",
                "x": 1.7,
                "y": 8.5,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "N",
                "offset": 0.8,
                "width": 1.4,
                "height": 1.2,
                "sill_m": 0.9
              },
              {
                "wall": "W",
                "offset": 0.8,
                "width": 1.2,
                "height": 1.2,
                "sill_m": 0.9
              }
            ]
          },
          {
            "name": "Master Bedroom",
            "rect": {
              "x": 0.3,
              "y": 2.5,
              "w": 2.94,
              "h": 4.38
            },
            "floor": "oak_parquet",
            "furniture": [
              {
                "type": "bed_double",
                "x": 1.7,
                "y": 4.5,
                "rotation_deg": 0
              },
              {
                "type": "side_table",
                "x": 0.6,
                "y": 5.5,
                "rotation_deg": 0
              },
              {
                "type": "side_table",
                "x": 2.8,
                "y": 5.5,
                "rotation_deg": 0
              },
              {
                "type": "wardrobe",
                "x": 0.6,
                "y": 3.2,
                "rotation_deg": 90
              },
              {
                "type": "ceiling_fan",
                "x": 1.7,
                "y": 4.5,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "W",
                "offset": 1.2,
                "width": 1.6,
                "height": 1.3,
                "sill_m": 0.9
              }
            ]
          },
          {
            "name": "Bath & WC",
            "rect": {
              "x": 0.3,
              "y": 0.9,
              "w": 1.92,
              "h": 1.38
            },
            "floor": "ceramic_tile",
            "furniture": [
              {
                "type": "toilet",
                "x": 0.8,
                "y": 1.6,
                "rotation_deg": 0
              },
              {
                "type": "sink",
                "x": 1.8,
                "y": 1.6,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "W",
                "offset": 0.4,
                "width": 0.7,
                "height": 0.6,
                "sill_m": 1.8
              }
            ]
          }
        ],
        "doors": [
          {
            "from": "Sit-Out & Foyer",
            "to": "Living / Hall",
            "x": 4.8,
            "y": 1.6,
            "width": 1,
            "wall": "N",
            "style": "teak",
            "name": "Main Entrance Door"
          },
          {
            "from": "Living / Hall",
            "to": "Dining Room",
            "x": 4.8,
            "y": 5.4,
            "width": 1.1,
            "wall": "N",
            "name": "Dining Archway"
          },
          {
            "from": "Dining Room",
            "to": "Kitchen",
            "x": 6.6,
            "y": 8,
            "width": 0.9,
            "wall": "E",
            "name": "Kitchen Entry"
          },
          {
            "from": "Dining Room",
            "to": "Store Room",
            "x": 7.5,
            "y": 6.2,
            "width": 0.75,
            "wall": "E",
            "name": "Store Door"
          },
          {
            "from": "Dining Room",
            "to": "Bedroom 1",
            "x": 3.3,
            "y": 7.8,
            "width": 0.9,
            "wall": "W",
            "name": "Bed 1 Door"
          },
          {
            "from": "Living / Hall",
            "to": "Master Bedroom",
            "x": 2.1,
            "y": 3.8,
            "width": 0.9,
            "wall": "W",
            "name": "Master Bed Door"
          },
          {
            "from": "Master Bedroom",
            "to": "Bath & WC",
            "x": 1.2,
            "y": 2.4,
            "width": 0.75,
            "wall": "S",
            "name": "Bath Door"
          }
        ],
        "camera_tour": [
          {
            "x": 4.8,
            "y": 0.6,
            "z": 1.4,
            "look_at": [
              4.8,
              3.2,
              1.3
            ]
          },
          {
            "x": 4.8,
            "y": 3.2,
            "z": 1.5,
            "look_at": [
              4.8,
              7.5,
              1.4
            ]
          },
          {
            "x": 4.8,
            "y": 7.5,
            "z": 1.5,
            "look_at": [
              8,
              8.5,
              1.3
            ]
          },
          {
            "x": 1.7,
            "y": 4.5,
            "z": 1.5,
            "look_at": [
              1.7,
              5.5,
              1.2
            ]
          }
        ]
      },
      "vastu": {
        "compliance_score": 94,
        "grade": "Optimal",
        "rooms": [
          {
            "name": "Master Bedroom",
            "status": "best",
            "score": 98,
            "note": "Perfect South-West placement with high thermal lag"
          },
          {
            "name": "Kitchen",
            "status": "best",
            "score": 96,
            "note": "Ideal South-East Agni corner placement"
          },
          {
            "name": "Dining Room",
            "status": "good",
            "score": 92,
            "note": "Harmonious North zone family dining"
          },
          {
            "name": "Living / Hall",
            "status": "good",
            "score": 94,
            "note": "Expansive solar daylit core"
          },
          {
            "name": "Bedroom 1",
            "status": "good",
            "score": 90,
            "note": "Vayu northwest orientation"
          },
          {
            "name": "Sit-Out & Foyer",
            "status": "best",
            "score": 95,
            "note": "Auspicious transitional entrance"
          }
        ]
      }
    },
    {
      "id": "plan-2",
      "property": {
        "id": "plan-2",
        "name": "Plan 2: 4 BHK Suburban Residence (960 sq.ft)",
        "description": "Optimized 4 BHK layout (8.00m \u00d7 9.50m). Porch entry, multi-bedroom efficiency.",
        "facing": "S",
        "north_rotation_deg": 0,
        "dimensions_m": {
          "width": 8,
          "depth": 9.5
        },
        "area_sqft": 960,
        "area_m2": 89.2,
        "bhk": 4,
        "rooms": [
          {
            "name": "Front Porch",
            "vastu_item": "Entrance",
            "direction": "South"
          },
          {
            "name": "Living Room",
            "vastu_item": "Living & Dining",
            "direction": "SE"
          },
          {
            "name": "Dining Room",
            "vastu_item": "Dining Room",
            "direction": "Center"
          },
          {
            "name": "Kitchen",
            "vastu_item": "Kitchen",
            "direction": "SE"
          },
          {
            "name": "Master Bedroom",
            "vastu_item": "Master Bedroom",
            "direction": "NW"
          },
          {
            "name": "Bedroom 4",
            "vastu_item": "Bedroom",
            "direction": "NE"
          },
          {
            "name": "Bedroom 2",
            "vastu_item": "Bedroom",
            "direction": "Center-East"
          },
          {
            "name": "Bedroom 1",
            "vastu_item": "Bedroom",
            "direction": "SE"
          },
          {
            "name": "Common Bath",
            "vastu_item": "Toilet/Bath",
            "direction": "West"
          }
        ]
      },
      "layout": {
        "wall_height_m": 2.85,
        "wall_thickness_m": 0.2,
        "style": "suburban_4bhk",
        "rooms": [
          {
            "name": "Front Porch",
            "rect": {
              "x": 0.2,
              "y": 0.2,
              "w": 4.12,
              "h": 2
            },
            "floor": "ceramic_tile",
            "furniture": [
              {
                "type": "shoe_rack",
                "x": 0.6,
                "y": 0.5,
                "rotation_deg": 0
              },
              {
                "type": "plant",
                "x": 3.8,
                "y": 0.5,
                "rotation_deg": 0
              }
            ],
            "windows": []
          },
          {
            "name": "Living Room",
            "rect": {
              "x": 0.2,
              "y": 2.3,
              "w": 4,
              "h": 2.7
            },
            "floor": "oak_parquet",
            "furniture": [
              {
                "type": "sofa",
                "x": 2.2,
                "y": 4.1,
                "rotation_deg": 0
              },
              {
                "type": "coffee_table",
                "x": 2.2,
                "y": 3.3,
                "rotation_deg": 0
              },
              {
                "type": "tv_unit",
                "x": 2.2,
                "y": 2.5,
                "rotation_deg": 0
              },
              {
                "type": "ceiling_fan",
                "x": 2.2,
                "y": 3.5,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "W",
                "offset": 0.6,
                "width": 1.4,
                "height": 1.2,
                "sill_m": 0.9
              }
            ]
          },
          {
            "name": "Dining Room",
            "rect": {
              "x": 0.2,
              "y": 5.1,
              "w": 4,
              "h": 2
            },
            "floor": "marble_white",
            "furniture": [
              {
                "type": "dining_table",
                "x": 2.2,
                "y": 6.1,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "W",
                "offset": 0.5,
                "width": 1.2,
                "height": 1.2,
                "sill_m": 0.9
              }
            ]
          },
          {
            "name": "Kitchen",
            "rect": {
              "x": 4.3,
              "y": 5.1,
              "w": 3.5,
              "h": 2
            },
            "floor": "ceramic_tile",
            "furniture": [
              {
                "type": "kitchen_counter",
                "x": 7.2,
                "y": 6,
                "rotation_deg": 90
              },
              {
                "type": "stove",
                "x": 7.2,
                "y": 6.6,
                "rotation_deg": 90
              },
              {
                "type": "fridge",
                "x": 4.6,
                "y": 6.8,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "E",
                "offset": 0.6,
                "width": 1.2,
                "height": 1,
                "sill_m": 1
              }
            ]
          },
          {
            "name": "Master Bedroom",
            "rect": {
              "x": 0.2,
              "y": 7.2,
              "w": 3.8,
              "h": 2.1
            },
            "floor": "oak_parquet",
            "furniture": [
              {
                "type": "bed_double",
                "x": 2.1,
                "y": 8.2,
                "rotation_deg": 0
              },
              {
                "type": "side_table",
                "x": 0.7,
                "y": 8.8,
                "rotation_deg": 0
              },
              {
                "type": "wardrobe",
                "x": 0.6,
                "y": 7.6,
                "rotation_deg": 90
              },
              {
                "type": "ceiling_fan",
                "x": 2.1,
                "y": 8.2,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "N",
                "offset": 0.8,
                "width": 1.4,
                "height": 1.2,
                "sill_m": 0.9
              },
              {
                "wall": "W",
                "offset": 0.5,
                "width": 1.2,
                "height": 1.2,
                "sill_m": 0.9
              }
            ]
          },
          {
            "name": "Bedroom 4",
            "rect": {
              "x": 4.1,
              "y": 7.2,
              "w": 3.7,
              "h": 2.1
            },
            "floor": "oak_parquet",
            "furniture": [
              {
                "type": "bed_double",
                "x": 5.9,
                "y": 8.2,
                "rotation_deg": 0
              },
              {
                "type": "side_table",
                "x": 7.3,
                "y": 8.8,
                "rotation_deg": 0
              },
              {
                "type": "wardrobe",
                "x": 4.5,
                "y": 7.6,
                "rotation_deg": 90
              }
            ],
            "windows": [
              {
                "wall": "N",
                "offset": 1,
                "width": 1.4,
                "height": 1.2,
                "sill_m": 0.9
              },
              {
                "wall": "E",
                "offset": 0.6,
                "width": 1.2,
                "height": 1.2,
                "sill_m": 0.9
              }
            ]
          },
          {
            "name": "Bedroom 1",
            "rect": {
              "x": 4.4,
              "y": 0.2,
              "w": 3.4,
              "h": 2.35
            },
            "floor": "oak_parquet",
            "furniture": [
              {
                "type": "bed_single",
                "x": 6.1,
                "y": 1.3,
                "rotation_deg": 0
              },
              {
                "type": "study_desk",
                "x": 4.8,
                "y": 0.6,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "S",
                "offset": 0.6,
                "width": 1.2,
                "height": 1.2,
                "sill_m": 0.9
              },
              {
                "wall": "E",
                "offset": 0.6,
                "width": 1.2,
                "height": 1.2,
                "sill_m": 0.9
              }
            ]
          },
          {
            "name": "Bedroom 2",
            "rect": {
              "x": 4.4,
              "y": 2.65,
              "w": 3.4,
              "h": 2.35
            },
            "floor": "oak_parquet",
            "furniture": [
              {
                "type": "bed_single",
                "x": 6.1,
                "y": 3.8,
                "rotation_deg": 0
              },
              {
                "type": "study_desk",
                "x": 4.8,
                "y": 4.5,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "E",
                "offset": 0.6,
                "width": 1.2,
                "height": 1.2,
                "sill_m": 0.9
              }
            ]
          },
          {
            "name": "Common Bath",
            "rect": {
              "x": 3.2,
              "y": 4.8,
              "w": 1,
              "h": 1.8
            },
            "floor": "ceramic_tile",
            "furniture": [
              {
                "type": "toilet",
                "x": 3.7,
                "y": 5.5,
                "rotation_deg": 0
              }
            ],
            "windows": []
          }
        ],
        "doors": [
          {
            "from": "Front Porch",
            "to": "Living Room",
            "x": 2.2,
            "y": 2.2,
            "width": 1,
            "wall": "N",
            "style": "teak",
            "name": "Main Entrance"
          },
          {
            "from": "Living Room",
            "to": "Dining Room",
            "x": 2.2,
            "y": 5,
            "width": 1,
            "wall": "N",
            "name": "Dining Opening"
          },
          {
            "from": "Dining Room",
            "to": "Kitchen",
            "x": 4.2,
            "y": 6.1,
            "width": 0.9,
            "wall": "E",
            "name": "Kitchen Entry"
          },
          {
            "from": "Dining Room",
            "to": "Master Bedroom",
            "x": 1.8,
            "y": 7.1,
            "width": 0.9,
            "wall": "N",
            "name": "Master Bed Entry"
          },
          {
            "from": "Dining Room",
            "to": "Bedroom 4",
            "x": 5,
            "y": 7.1,
            "width": 0.9,
            "wall": "N",
            "name": "Bed 4 Entry"
          },
          {
            "from": "Living Room",
            "to": "Bedroom 2",
            "x": 4.3,
            "y": 3.8,
            "width": 0.85,
            "wall": "E",
            "name": "Bed 2 Entry"
          },
          {
            "from": "Front Porch",
            "to": "Bedroom 1",
            "x": 4.3,
            "y": 1.3,
            "width": 0.85,
            "wall": "E",
            "name": "Bed 1 Entry"
          }
        ],
        "camera_tour": [
          {
            "x": 2.2,
            "y": 1,
            "z": 1.4,
            "look_at": [
              2.2,
              3.5,
              1.4
            ]
          },
          {
            "x": 2.2,
            "y": 3.5,
            "z": 1.5,
            "look_at": [
              2.2,
              6.1,
              1.4
            ]
          },
          {
            "x": 2.2,
            "y": 6.1,
            "z": 1.5,
            "look_at": [
              5.5,
              6.1,
              1.3
            ]
          },
          {
            "x": 2.1,
            "y": 8.2,
            "z": 1.5,
            "look_at": [
              2.1,
              9,
              1.3
            ]
          }
        ]
      },
      "vastu": {
        "compliance_score": 92,
        "grade": "Optimal",
        "rooms": [
          {
            "name": "Living Room",
            "status": "good",
            "score": 92,
            "note": "Warm southern daylit gathering space"
          },
          {
            "name": "Kitchen",
            "status": "best",
            "score": 95,
            "note": "East-facing cooking zone"
          },
          {
            "name": "Master Bedroom",
            "status": "good",
            "score": 90,
            "note": "Quiet northern zone"
          },
          {
            "name": "Front Porch",
            "status": "best",
            "score": 94,
            "note": "Generous climate buffer transition"
          }
        ]
      }
    },
    {
      "id": "plan-3",
      "property": {
        "id": "plan-3",
        "name": "Plan 3: 5 BHK Luxury Manor (1,240 sq.ft)",
        "description": "Generous 5 BHK multi-generational manor (12.80m \u00d7 9.00m). Dual living zones, chef kitchen.",
        "facing": "E",
        "north_rotation_deg": 0,
        "dimensions_m": {
          "width": 12.8,
          "depth": 9
        },
        "area_sqft": 1240,
        "area_m2": 115.2,
        "bhk": 5,
        "rooms": [
          {
            "name": "Grand Family Living",
            "vastu_item": "Living & Dining",
            "direction": "NE"
          },
          {
            "name": "Dining Hall",
            "vastu_item": "Dining Room",
            "direction": "North"
          },
          {
            "name": "Chef's Kitchen",
            "vastu_item": "Kitchen",
            "direction": "SE"
          },
          {
            "name": "Master Suite",
            "vastu_item": "Master Bedroom",
            "direction": "SW"
          },
          {
            "name": "Bedroom 1 (NW)",
            "vastu_item": "Bedroom",
            "direction": "NW"
          },
          {
            "name": "Bedroom 2 (North)",
            "vastu_item": "Bedroom",
            "direction": "North"
          },
          {
            "name": "Bedroom 4 (West)",
            "vastu_item": "Bedroom",
            "direction": "West"
          },
          {
            "name": "Bedroom 5 (South)",
            "vastu_item": "Bedroom",
            "direction": "South"
          }
        ]
      },
      "layout": {
        "wall_height_m": 2.85,
        "wall_thickness_m": 0.2,
        "style": "luxury_manor",
        "rooms": [
          {
            "name": "Grand Family Living",
            "rect": {
              "x": 4,
              "y": 2.5,
              "w": 4.8,
              "h": 3.8
            },
            "floor": "marble_white",
            "furniture": [
              {
                "type": "sofa",
                "x": 6.4,
                "y": 4.8,
                "rotation_deg": 0
              },
              {
                "type": "coffee_table",
                "x": 6.4,
                "y": 3.9,
                "rotation_deg": 0
              },
              {
                "type": "tv_unit",
                "x": 6.4,
                "y": 2.8,
                "rotation_deg": 0
              },
              {
                "type": "ceiling_fan",
                "x": 6.4,
                "y": 4.2,
                "rotation_deg": 0
              },
              {
                "type": "plant",
                "x": 4.5,
                "y": 5.8,
                "rotation_deg": 0
              },
              {
                "type": "plant",
                "x": 8.3,
                "y": 5.8,
                "rotation_deg": 0
              }
            ],
            "windows": []
          },
          {
            "name": "Dining Hall",
            "rect": {
              "x": 4,
              "y": 6.4,
              "w": 4.8,
              "h": 2.4
            },
            "floor": "marble_cream",
            "furniture": [
              {
                "type": "dining_table",
                "x": 6.4,
                "y": 7.6,
                "rotation_deg": 0
              },
              {
                "type": "pendant_light",
                "x": 6.4,
                "y": 7.6,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "N",
                "offset": 1.6,
                "width": 1.6,
                "height": 1.3,
                "sill_m": 0.9
              }
            ]
          },
          {
            "name": "Chef's Kitchen",
            "rect": {
              "x": 8.9,
              "y": 6.2,
              "w": 3.7,
              "h": 2.6
            },
            "floor": "ceramic_tile",
            "furniture": [
              {
                "type": "kitchen_counter",
                "x": 12,
                "y": 7.5,
                "rotation_deg": 90
              },
              {
                "type": "stove",
                "x": 12,
                "y": 8.2,
                "rotation_deg": 90
              },
              {
                "type": "fridge",
                "x": 9.3,
                "y": 8.4,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "N",
                "offset": 0.8,
                "width": 1.2,
                "height": 1.1,
                "sill_m": 1
              },
              {
                "wall": "E",
                "offset": 0.8,
                "width": 1.4,
                "height": 1.1,
                "sill_m": 1
              }
            ]
          },
          {
            "name": "Master Suite",
            "rect": {
              "x": 8.9,
              "y": 0.2,
              "w": 3.7,
              "h": 3.4
            },
            "floor": "oak_parquet",
            "furniture": [
              {
                "type": "bed_double",
                "x": 10.7,
                "y": 1.9,
                "rotation_deg": 0
              },
              {
                "type": "side_table",
                "x": 9.4,
                "y": 2.8,
                "rotation_deg": 0
              },
              {
                "type": "side_table",
                "x": 12,
                "y": 2.8,
                "rotation_deg": 0
              },
              {
                "type": "wardrobe",
                "x": 9.3,
                "y": 0.7,
                "rotation_deg": 90
              },
              {
                "type": "ceiling_fan",
                "x": 10.7,
                "y": 1.9,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "S",
                "offset": 0.8,
                "width": 1.6,
                "height": 1.3,
                "sill_m": 0.9
              },
              {
                "wall": "E",
                "offset": 0.8,
                "width": 1.6,
                "height": 1.3,
                "sill_m": 0.9
              }
            ]
          },
          {
            "name": "Bedroom 1 (NW)",
            "rect": {
              "x": 0.2,
              "y": 5.8,
              "w": 3.6,
              "h": 3
            },
            "floor": "oak_parquet",
            "furniture": [
              {
                "type": "bed_double",
                "x": 2,
                "y": 7.3,
                "rotation_deg": 0
              },
              {
                "type": "wardrobe",
                "x": 0.6,
                "y": 6.2,
                "rotation_deg": 90
              }
            ],
            "windows": [
              {
                "wall": "N",
                "offset": 0.8,
                "width": 1.4,
                "height": 1.2,
                "sill_m": 0.9
              },
              {
                "wall": "W",
                "offset": 0.8,
                "width": 1.4,
                "height": 1.2,
                "sill_m": 0.9
              }
            ]
          },
          {
            "name": "Bedroom 2 (North)",
            "rect": {
              "x": 4,
              "y": 0.2,
              "w": 3.5,
              "h": 2.2
            },
            "floor": "oak_parquet",
            "furniture": [
              {
                "type": "bed_single",
                "x": 5.8,
                "y": 1.3,
                "rotation_deg": 0
              },
              {
                "type": "study_desk",
                "x": 4.5,
                "y": 0.6,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "S",
                "offset": 0.8,
                "width": 1.4,
                "height": 1.2,
                "sill_m": 0.9
              }
            ]
          },
          {
            "name": "Bedroom 4 (West)",
            "rect": {
              "x": 0.2,
              "y": 0.2,
              "w": 3.6,
              "h": 3.2
            },
            "floor": "oak_parquet",
            "furniture": [
              {
                "type": "bed_double",
                "x": 2,
                "y": 1.8,
                "rotation_deg": 0
              },
              {
                "type": "wardrobe",
                "x": 0.6,
                "y": 2.8,
                "rotation_deg": 90
              }
            ],
            "windows": [
              {
                "wall": "S",
                "offset": 0.8,
                "width": 1.4,
                "height": 1.2,
                "sill_m": 0.9
              },
              {
                "wall": "W",
                "offset": 0.8,
                "width": 1.4,
                "height": 1.2,
                "sill_m": 0.9
              }
            ]
          },
          {
            "name": "Bedroom 5 (South)",
            "rect": {
              "x": 0.2,
              "y": 3.5,
              "w": 3.6,
              "h": 2.2
            },
            "floor": "oak_parquet",
            "furniture": [
              {
                "type": "bed_single",
                "x": 2,
                "y": 4.6,
                "rotation_deg": 0
              },
              {
                "type": "study_desk",
                "x": 3.2,
                "y": 4,
                "rotation_deg": 90
              }
            ],
            "windows": [
              {
                "wall": "W",
                "offset": 0.6,
                "width": 1.4,
                "height": 1.2,
                "sill_m": 0.9
              }
            ]
          }
        ],
        "doors": [
          {
            "from": "Grand Family Living",
            "to": "Dining Hall",
            "x": 6.4,
            "y": 6.3,
            "width": 1.2,
            "wall": "N",
            "name": "Dining Passage"
          },
          {
            "from": "Dining Hall",
            "to": "Chef's Kitchen",
            "x": 8.8,
            "y": 7.5,
            "width": 1,
            "wall": "E",
            "name": "Kitchen Entry"
          },
          {
            "from": "Grand Family Living",
            "to": "Master Suite",
            "x": 8.8,
            "y": 2.5,
            "width": 1,
            "wall": "E",
            "name": "Master Suite Door"
          },
          {
            "from": "Dining Hall",
            "to": "Bedroom 1 (NW)",
            "x": 3.9,
            "y": 7.2,
            "width": 0.9,
            "wall": "W",
            "name": "Bed 1 Entry"
          },
          {
            "from": "Grand Family Living",
            "to": "Bedroom 5 (South)",
            "x": 3.9,
            "y": 4.5,
            "width": 0.9,
            "wall": "W",
            "name": "Bed 5 Entry"
          },
          {
            "from": "Grand Family Living",
            "to": "Bedroom 4 (West)",
            "x": 3.9,
            "y": 2,
            "width": 0.9,
            "wall": "W",
            "name": "Bed 4 Entry"
          },
          {
            "from": "Grand Family Living",
            "to": "Bedroom 2 (North)",
            "x": 5.7,
            "y": 2.4,
            "width": 0.9,
            "wall": "S",
            "name": "Bed 2 Entry"
          }
        ],
        "camera_tour": [
          {
            "x": 6.4,
            "y": 3,
            "z": 1.5,
            "look_at": [
              6.4,
              5,
              1.4
            ]
          },
          {
            "x": 6.4,
            "y": 6.4,
            "z": 1.5,
            "look_at": [
              10,
              7.5,
              1.4
            ]
          },
          {
            "x": 10.7,
            "y": 1.9,
            "z": 1.5,
            "look_at": [
              10.7,
              3,
              1.3
            ]
          },
          {
            "x": 2,
            "y": 7.3,
            "z": 1.5,
            "look_at": [
              2,
              8.5,
              1.3
            ]
          }
        ]
      },
      "vastu": {
        "compliance_score": 96,
        "grade": "Optimal",
        "rooms": [
          {
            "name": "Master Suite",
            "status": "best",
            "score": 98,
            "note": "South-West master sanctuary"
          },
          {
            "name": "Chef's Kitchen",
            "status": "best",
            "score": 96,
            "note": "South-East Agni placement"
          },
          {
            "name": "Grand Family Living",
            "status": "best",
            "score": 96,
            "note": "Central expansive core"
          },
          {
            "name": "Dining Hall",
            "status": "good",
            "score": 94,
            "note": "North harmonious dining"
          }
        ]
      }
    },
    {
      "id": "plan-4",
      "property": {
        "id": "plan-4",
        "name": "Plan 4: 1 BHK Minimalist Studio (483 sq.ft)",
        "description": "Orthogonal single-bedroom efficiency studio (7.28m \u00d7 6.17m = 23'-10\" \u00d7 20'-3\"). Daylit open floor plan.",
        "facing": "E",
        "north_rotation_deg": 0,
        "dimensions_m": {
          "width": 7.28,
          "depth": 6.17
        },
        "area_sqft": 483,
        "area_m2": 44.9,
        "bhk": 1,
        "rooms": [
          {
            "name": "Living Room",
            "vastu_item": "Living & Dining",
            "direction": "NE"
          },
          {
            "name": "Kitchen & Dining",
            "vastu_item": "Kitchen",
            "direction": "SE"
          },
          {
            "name": "Bedroom",
            "vastu_item": "Master Bedroom",
            "direction": "NW"
          },
          {
            "name": "Office Nook",
            "vastu_item": "Study",
            "direction": "North"
          },
          {
            "name": "Bathroom",
            "vastu_item": "Toilet/Bath",
            "direction": "West"
          }
        ]
      },
      "layout": {
        "wall_height_m": 2.7,
        "wall_thickness_m": 0.18,
        "style": "minimalist_studio",
        "rooms": [
          {
            "name": "Living Room",
            "rect": {
              "x": 0.2,
              "y": 0.2,
              "w": 3.8,
              "h": 3.4
            },
            "floor": "oak_parquet",
            "furniture": [
              {
                "type": "sofa",
                "x": 2.1,
                "y": 2.4,
                "rotation_deg": 0
              },
              {
                "type": "coffee_table",
                "x": 2.1,
                "y": 1.5,
                "rotation_deg": 0
              },
              {
                "type": "tv_unit",
                "x": 2.1,
                "y": 0.6,
                "rotation_deg": 0
              },
              {
                "type": "ceiling_fan",
                "x": 2.1,
                "y": 1.9,
                "rotation_deg": 0
              },
              {
                "type": "plant",
                "x": 0.6,
                "y": 0.6,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "S",
                "offset": 0.8,
                "width": 1.5,
                "height": 1.3,
                "sill_m": 0.9
              },
              {
                "wall": "W",
                "offset": 0.8,
                "width": 1.2,
                "height": 1.3,
                "sill_m": 0.9
              }
            ]
          },
          {
            "name": "Kitchen & Dining",
            "rect": {
              "x": 4.1,
              "y": 0.2,
              "w": 3,
              "h": 3.4
            },
            "floor": "ceramic_tile",
            "furniture": [
              {
                "type": "kitchen_counter",
                "x": 6.6,
                "y": 1.8,
                "rotation_deg": 90
              },
              {
                "type": "stove",
                "x": 6.6,
                "y": 2.6,
                "rotation_deg": 90
              },
              {
                "type": "fridge",
                "x": 4.5,
                "y": 3,
                "rotation_deg": 0
              },
              {
                "type": "dining_table",
                "x": 5.1,
                "y": 1.2,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "E",
                "offset": 0.8,
                "width": 1.4,
                "height": 1.2,
                "sill_m": 1
              },
              {
                "wall": "S",
                "offset": 0.6,
                "width": 1,
                "height": 1.2,
                "sill_m": 1
              }
            ]
          },
          {
            "name": "Bedroom",
            "rect": {
              "x": 0.2,
              "y": 3.7,
              "w": 3.8,
              "h": 2.3
            },
            "floor": "oak_parquet",
            "furniture": [
              {
                "type": "bed_double",
                "x": 2.1,
                "y": 4.8,
                "rotation_deg": 0
              },
              {
                "type": "side_table",
                "x": 0.7,
                "y": 5.5,
                "rotation_deg": 0
              },
              {
                "type": "side_table",
                "x": 3.4,
                "y": 5.5,
                "rotation_deg": 0
              },
              {
                "type": "wardrobe",
                "x": 0.6,
                "y": 4,
                "rotation_deg": 90
              },
              {
                "type": "ceiling_fan",
                "x": 2.1,
                "y": 4.8,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "N",
                "offset": 0.8,
                "width": 1.4,
                "height": 1.2,
                "sill_m": 0.9
              },
              {
                "wall": "W",
                "offset": 0.6,
                "width": 1.2,
                "height": 1.2,
                "sill_m": 0.9
              }
            ]
          },
          {
            "name": "Office Nook",
            "rect": {
              "x": 4.1,
              "y": 3.7,
              "w": 1.5,
              "h": 2.3
            },
            "floor": "oak_parquet",
            "furniture": [
              {
                "type": "study_desk",
                "x": 4.8,
                "y": 4.8,
                "rotation_deg": 0
              },
              {
                "type": "office_chair",
                "x": 4.8,
                "y": 4.2,
                "rotation_deg": 0
              },
              {
                "type": "floor_lamp",
                "x": 5.3,
                "y": 5.5,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "N",
                "offset": 0.3,
                "width": 0.9,
                "height": 1.2,
                "sill_m": 0.9
              }
            ]
          },
          {
            "name": "Bathroom",
            "rect": {
              "x": 5.7,
              "y": 3.7,
              "w": 1.4,
              "h": 2.3
            },
            "floor": "ceramic_tile",
            "furniture": [
              {
                "type": "toilet",
                "x": 6.4,
                "y": 4.4,
                "rotation_deg": 0
              },
              {
                "type": "sink",
                "x": 6.4,
                "y": 5.3,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "E",
                "offset": 0.4,
                "width": 0.6,
                "height": 0.6,
                "sill_m": 1.8
              }
            ]
          }
        ],
        "doors": [
          {
            "from": "Living Room",
            "to": "Kitchen & Dining",
            "x": 4,
            "y": 1.8,
            "width": 1.1,
            "wall": "E",
            "name": "Open Dining Portal"
          },
          {
            "from": "Living Room",
            "to": "Bedroom",
            "x": 2.1,
            "y": 3.6,
            "width": 0.9,
            "wall": "N",
            "name": "Bedroom Door"
          },
          {
            "from": "Kitchen & Dining",
            "to": "Office Nook",
            "x": 4.8,
            "y": 3.6,
            "width": 0.85,
            "wall": "N",
            "name": "Office Entry"
          },
          {
            "from": "Office Nook",
            "to": "Bathroom",
            "x": 5.6,
            "y": 4.8,
            "width": 0.75,
            "wall": "E",
            "name": "Bathroom Door"
          }
        ],
        "camera_tour": [
          {
            "x": 2.1,
            "y": 1,
            "z": 1.4,
            "look_at": [
              2.1,
              2.5,
              1.3
            ]
          },
          {
            "x": 5.2,
            "y": 1.8,
            "z": 1.4,
            "look_at": [
              6.4,
              2.4,
              1.3
            ]
          },
          {
            "x": 2.1,
            "y": 4.8,
            "z": 1.4,
            "look_at": [
              2.1,
              5.5,
              1.2
            ]
          },
          {
            "x": 4.8,
            "y": 4.5,
            "z": 1.4,
            "look_at": [
              4.8,
              5.5,
              1.2
            ]
          }
        ]
      },
      "vastu": {
        "compliance_score": 93,
        "grade": "Optimal",
        "rooms": [
          {
            "name": "Living Room",
            "status": "best",
            "score": 95,
            "note": "Bright open daytime quadrant"
          },
          {
            "name": "Kitchen & Dining",
            "status": "best",
            "score": 94,
            "note": "Southeast cooking zone"
          },
          {
            "name": "Bedroom",
            "status": "good",
            "score": 91,
            "note": "Quiet northwest sanctuary"
          },
          {
            "name": "Office Nook",
            "status": "best",
            "score": 95,
            "note": "North clarity study orientation"
          }
        ]
      }
    },
    {
      "id": "plan-5",
      "property": {
        "id": "plan-5",
        "name": "Plan 5: 1 BHK Solar Chamfer Villa (495 sq.ft)",
        "description": "Bioclimatic angled wall residence (8.15m \u00d7 7.01m = 26'-9\" \u00d7 23'-0\"). 15'-4\" Chamfer facade engineered for peak solar gain.",
        "facing": "S",
        "north_rotation_deg": 0,
        "dimensions_m": {
          "width": 8.15,
          "depth": 7.01
        },
        "area_sqft": 495,
        "area_m2": 46,
        "bhk": 1,
        "rooms": [
          {
            "name": "Daylit Living Room",
            "vastu_item": "Living & Dining",
            "direction": "South"
          },
          {
            "name": "Entrance Foyer",
            "vastu_item": "Entrance",
            "direction": "SE"
          },
          {
            "name": "Master Bedroom",
            "vastu_item": "Master Bedroom",
            "direction": "SW"
          },
          {
            "name": "Gourmet Kitchen",
            "vastu_item": "Kitchen",
            "direction": "SE"
          },
          {
            "name": "Full Bathroom",
            "vastu_item": "Toilet/Bath",
            "direction": "East"
          }
        ]
      },
      "layout": {
        "wall_height_m": 2.75,
        "wall_thickness_m": 0.2,
        "style": "solar_chamfer",
        "rooms": [
          {
            "name": "Daylit Living Room",
            "rect": {
              "x": 0.2,
              "y": 0.2,
              "w": 4.6,
              "h": 3.6
            },
            "floor": "oak_parquet",
            "furniture": [
              {
                "type": "sofa",
                "x": 2.5,
                "y": 2.6,
                "rotation_deg": 0
              },
              {
                "type": "coffee_table",
                "x": 2.5,
                "y": 1.7,
                "rotation_deg": 0
              },
              {
                "type": "tv_unit",
                "x": 2.5,
                "y": 0.6,
                "rotation_deg": 0
              },
              {
                "type": "floor_lamp",
                "x": 0.6,
                "y": 3.2,
                "rotation_deg": 0
              },
              {
                "type": "plant",
                "x": 4.2,
                "y": 3.2,
                "rotation_deg": 0
              },
              {
                "type": "ceiling_fan",
                "x": 2.5,
                "y": 2,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "S",
                "offset": 1,
                "width": 2.2,
                "height": 1.4,
                "sill_m": 0.8
              },
              {
                "wall": "W",
                "offset": 1,
                "width": 1.4,
                "height": 1.4,
                "sill_m": 0.8
              }
            ]
          },
          {
            "name": "Entrance Foyer",
            "rect": {
              "x": 4.9,
              "y": 0.2,
              "w": 3,
              "h": 1.8
            },
            "floor": "ceramic_tile",
            "furniture": [
              {
                "type": "shoe_rack",
                "x": 5.4,
                "y": 0.6,
                "rotation_deg": 0
              },
              {
                "type": "console_table",
                "x": 7.2,
                "y": 1,
                "rotation_deg": 90
              }
            ],
            "windows": []
          },
          {
            "name": "Master Bedroom",
            "rect": {
              "x": 0.2,
              "y": 3.9,
              "w": 4.2,
              "h": 2.9
            },
            "floor": "oak_parquet",
            "furniture": [
              {
                "type": "bed_double",
                "x": 2.3,
                "y": 5.2,
                "rotation_deg": 0
              },
              {
                "type": "side_table",
                "x": 0.8,
                "y": 6.1,
                "rotation_deg": 0
              },
              {
                "type": "side_table",
                "x": 3.8,
                "y": 6.1,
                "rotation_deg": 0
              },
              {
                "type": "wardrobe",
                "x": 0.6,
                "y": 4.2,
                "rotation_deg": 90
              },
              {
                "type": "ceiling_fan",
                "x": 2.3,
                "y": 5.2,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "N",
                "offset": 0.8,
                "width": 1.6,
                "height": 1.3,
                "sill_m": 0.9
              },
              {
                "wall": "W",
                "offset": 0.8,
                "width": 1.4,
                "height": 1.3,
                "sill_m": 0.9
              }
            ]
          },
          {
            "name": "Gourmet Kitchen",
            "rect": {
              "x": 4.9,
              "y": 2.1,
              "w": 3,
              "h": 2.6
            },
            "floor": "ceramic_tile",
            "furniture": [
              {
                "type": "kitchen_counter",
                "x": 7.4,
                "y": 3.4,
                "rotation_deg": 90
              },
              {
                "type": "stove",
                "x": 7.4,
                "y": 4.1,
                "rotation_deg": 90
              },
              {
                "type": "fridge",
                "x": 5.2,
                "y": 4.3,
                "rotation_deg": 0
              },
              {
                "type": "dining_chair",
                "x": 5.4,
                "y": 2.4,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "E",
                "offset": 0.6,
                "width": 1.4,
                "height": 1.2,
                "sill_m": 1
              }
            ]
          },
          {
            "name": "Full Bathroom",
            "rect": {
              "x": 4.9,
              "y": 4.8,
              "w": 3,
              "h": 2
            },
            "floor": "ceramic_tile",
            "furniture": [
              {
                "type": "toilet",
                "x": 5.6,
                "y": 5.8,
                "rotation_deg": 0
              },
              {
                "type": "sink",
                "x": 7.2,
                "y": 5.8,
                "rotation_deg": 0
              }
            ],
            "windows": [
              {
                "wall": "E",
                "offset": 0.6,
                "width": 0.8,
                "height": 0.6,
                "sill_m": 1.8
              },
              {
                "wall": "N",
                "offset": 0.6,
                "width": 0.8,
                "height": 0.6,
                "sill_m": 1.8
              }
            ]
          }
        ],
        "doors": [
          {
            "from": "Entrance Foyer",
            "to": "Daylit Living Room",
            "x": 4.8,
            "y": 1.2,
            "width": 1,
            "wall": "W",
            "name": "Foyer Archway"
          },
          {
            "from": "Daylit Living Room",
            "to": "Master Bedroom",
            "x": 2.3,
            "y": 3.8,
            "width": 0.9,
            "wall": "N",
            "name": "Master Bedroom Door"
          },
          {
            "from": "Daylit Living Room",
            "to": "Gourmet Kitchen",
            "x": 4.8,
            "y": 2.8,
            "width": 0.9,
            "wall": "E",
            "name": "Kitchen Opening"
          },
          {
            "from": "Gourmet Kitchen",
            "to": "Full Bathroom",
            "x": 6.4,
            "y": 4.7,
            "width": 0.75,
            "wall": "N",
            "name": "Bathroom Door"
          }
        ],
        "camera_tour": [
          {
            "x": 6,
            "y": 0.8,
            "z": 1.4,
            "look_at": [
              2.5,
              2,
              1.3
            ]
          },
          {
            "x": 2.5,
            "y": 2,
            "z": 1.5,
            "look_at": [
              2.5,
              5.2,
              1.4
            ]
          },
          {
            "x": 6.4,
            "y": 3.4,
            "z": 1.5,
            "look_at": [
              7.4,
              3.4,
              1.3
            ]
          },
          {
            "x": 2.3,
            "y": 5.2,
            "z": 1.5,
            "look_at": [
              2.3,
              6.2,
              1.3
            ]
          }
        ]
      },
      "vastu": {
        "compliance_score": 95,
        "grade": "Optimal",
        "rooms": [
          {
            "name": "Daylit Living Room",
            "status": "best",
            "score": 98,
            "note": "Solar chamfer passive gain collector"
          },
          {
            "name": "Master Bedroom",
            "status": "best",
            "score": 96,
            "note": "South-West thermal mass stability"
          },
          {
            "name": "Gourmet Kitchen",
            "status": "good",
            "score": 93,
            "note": "South-East Agni fire zone"
          },
          {
            "name": "Entrance Foyer",
            "status": "best",
            "score": 94,
            "note": "Shaded solar thermal buffer"
          }
        ]
      }
    }
  ]
};
