#!/usr/bin/env python3
"""
Parametric FreeCAD 3D CAD & STEP Solid Builder for Plan 3: 5 BHK Luxury Manor (1,240 sq.ft)
Auto-generated by ThermaBuild BIM Engine.
"""

import sys
import os

try:
    import FreeCAD as App
    import Part
except ImportError:
    print("FreeCAD Python API not found. To build solid STEP CAD model:")
    print("Run: FreeCADCmd generate_cad.py")
    sys.exit(0)

doc = App.newDocument("ThermaBuild_plan_3")

# 1. Foundation Slab (Reinforced Concrete Plinth)
slab = Part.makeBox(13400.0, 9600.0, 150)
slab.translate(App.Vector(-300, -300, 0))
slab_obj = doc.addObject("Part::Feature", "Foundation_Slab")
slab_obj.Shape = slab

# 2. Roof Slab (High-Thermal Insulation Overdeck)
roof = Part.makeBox(13600.0, 9800.0, 150)
roof.translate(App.Vector(-400, -400, 3000.0))
roof_obj = doc.addObject("Part::Feature", "Roof_Slab")
roof_obj.Shape = roof

# 3. Exterior Envelope Perimeter Walls
w_s = Part.makeBox(12800.0, 200.0, 2850.0)
w_s.translate(App.Vector(0, 0, 150))
doc.addObject("Part::Feature", "Wall_South").Shape = w_s

w_n = Part.makeBox(12800.0, 200.0, 2850.0)
w_n.translate(App.Vector(0, 8800.0, 150))
doc.addObject("Part::Feature", "Wall_North").Shape = w_n

w_w = Part.makeBox(200.0, 8600.0, 2850.0)
w_w.translate(App.Vector(0, 200.0, 150))
doc.addObject("Part::Feature", "Wall_West").Shape = w_w

w_e = Part.makeBox(200.0, 8600.0, 2850.0)
w_e.translate(App.Vector(12600.0, 200.0, 150))
doc.addObject("Part::Feature", "Wall_East").Shape = w_e

# 4. Interior Room Zones & Partitions

# Room 1: Grand Family Living (4.8m x 3.8m)
r_box = Part.makeBox(4800.0, 3800.0, 30)
r_box.translate(App.Vector(4000.0, 2500.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_1_Grand_Family_Living")
r_obj.Shape = r_box

# Room 2: Dining Hall (4.8m x 2.4m)
r_box = Part.makeBox(4800.0, 2400.0, 30)
r_box.translate(App.Vector(4000.0, 6400.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_2_Dining_Hall")
r_obj.Shape = r_box

# Room 3: Chef's Kitchen (3.7m x 2.6m)
r_box = Part.makeBox(3700.0, 2600.0, 30)
r_box.translate(App.Vector(8900.0, 6200.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_3_Chef's_Kitchen")
r_obj.Shape = r_box

# Room 4: Master Suite (3.7m x 3.4m)
r_box = Part.makeBox(3700.0, 3400.0, 30)
r_box.translate(App.Vector(8900.0, 200.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_4_Master_Suite")
r_obj.Shape = r_box

# Room 5: Bedroom 1 (NW) (3.6m x 3m)
r_box = Part.makeBox(3600.0, 3000.0, 30)
r_box.translate(App.Vector(200.0, 5800.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_5_Bedroom_1_(NW)")
r_obj.Shape = r_box

# Room 6: Bedroom 2 (North) (3.5m x 2.2m)
r_box = Part.makeBox(3500.0, 2200.0, 30)
r_box.translate(App.Vector(4000.0, 200.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_6_Bedroom_2_(North)")
r_obj.Shape = r_box

# Room 7: Bedroom 4 (West) (3.6m x 3.2m)
r_box = Part.makeBox(3600.0, 3200.0, 30)
r_box.translate(App.Vector(200.0, 200.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_7_Bedroom_4_(West)")
r_obj.Shape = r_box

# Room 8: Bedroom 5 (South) (3.6m x 2.2m)
r_box = Part.makeBox(3600.0, 2200.0, 30)
r_box.translate(App.Vector(200.0, 3500.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_8_Bedroom_5_(South)")
r_obj.Shape = r_box


doc.recompute()
step_path = os.path.join(os.path.dirname(__file__), "house.step")
Part.export([slab_obj, roof_obj], step_path)
print(f"Exported parametric solid CAD STEP: {step_path}")

fcstd_path = os.path.join(os.path.dirname(__file__), "house.FCStd")
doc.saveAs(fcstd_path)
print(f"Saved native FreeCAD project: {fcstd_path}")
