#!/usr/bin/env python3
"""
Parametric FreeCAD 3D CAD & STEP Solid Builder for Plan 4: 1 BHK Minimalist Studio (483 sq.ft)
Auto-generated by ThermaBuild BIM Engine.
"""

import sys
import os

try:
    import FreeCAD as App
    import Part
except ImportError:
    print("FreeCAD Python API not found. To build solid STEP CAD model:")
    print("Run: FreeCADCmd generate_cad.py")
    sys.exit(0)

doc = App.newDocument("ThermaBuild_plan_4")

# 1. Foundation Slab (Reinforced Concrete Plinth)
slab = Part.makeBox(7880.0, 6770.0, 150)
slab.translate(App.Vector(-300, -300, 0))
slab_obj = doc.addObject("Part::Feature", "Foundation_Slab")
slab_obj.Shape = slab

# 2. Roof Slab (High-Thermal Insulation Overdeck)
roof = Part.makeBox(8080.0, 6970.0, 150)
roof.translate(App.Vector(-400, -400, 2850.0))
roof_obj = doc.addObject("Part::Feature", "Roof_Slab")
roof_obj.Shape = roof

# 3. Exterior Envelope Perimeter Walls
w_s = Part.makeBox(7280.0, 180.0, 2700.0)
w_s.translate(App.Vector(0, 0, 150))
doc.addObject("Part::Feature", "Wall_South").Shape = w_s

w_n = Part.makeBox(7280.0, 180.0, 2700.0)
w_n.translate(App.Vector(0, 5990.0, 150))
doc.addObject("Part::Feature", "Wall_North").Shape = w_n

w_w = Part.makeBox(180.0, 5810.0, 2700.0)
w_w.translate(App.Vector(0, 180.0, 150))
doc.addObject("Part::Feature", "Wall_West").Shape = w_w

w_e = Part.makeBox(180.0, 5810.0, 2700.0)
w_e.translate(App.Vector(7100.0, 180.0, 150))
doc.addObject("Part::Feature", "Wall_East").Shape = w_e

# 4. Interior Room Zones & Partitions

# Room 1: Living Room (3.8m x 3.4m)
r_box = Part.makeBox(3800.0, 3400.0, 30)
r_box.translate(App.Vector(200.0, 200.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_1_Living_Room")
r_obj.Shape = r_box

# Room 2: Kitchen & Dining (3m x 3.4m)
r_box = Part.makeBox(3000.0, 3400.0, 30)
r_box.translate(App.Vector(4100.0, 200.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_2_Kitchen_and_Dining")
r_obj.Shape = r_box

# Room 3: Bedroom (3.8m x 2.3m)
r_box = Part.makeBox(3800.0, 2300.0, 30)
r_box.translate(App.Vector(200.0, 3700.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_3_Bedroom")
r_obj.Shape = r_box

# Room 4: Office Nook (1.5m x 2.3m)
r_box = Part.makeBox(1500.0, 2300.0, 30)
r_box.translate(App.Vector(4100.0, 3700.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_4_Office_Nook")
r_obj.Shape = r_box

# Room 5: Bathroom (1.4m x 2.3m)
r_box = Part.makeBox(1400.0, 2300.0, 30)
r_box.translate(App.Vector(5700.0, 3700.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_5_Bathroom")
r_obj.Shape = r_box


doc.recompute()
step_path = os.path.join(os.path.dirname(__file__), "house.step")
Part.export([slab_obj, roof_obj], step_path)
print(f"Exported parametric solid CAD STEP: {step_path}")

fcstd_path = os.path.join(os.path.dirname(__file__), "house.FCStd")
doc.saveAs(fcstd_path)
print(f"Saved native FreeCAD project: {fcstd_path}")
