#!/usr/bin/env python3
"""
ThermaBuild Animal Husbandry Bioclimatic Engine.
Solves species-specific thermal heat balance, Temperature-Humidity Index (THI),
natural ventilation rates (stack chimney + cross-draft), solar heat ingress,
and livestock productivity preservation for Cattle, Goats, and Poultry.
"""

from __future__ import annotations
import math
from typing import Any, Dict

# Material Thermal Properties (U-value W/m²K, Solar Absorptance alpha, Thermal Mass J/kgK)
MATERIALS_DATABASE = {
    "thatch_bamboo": {
        "name": "Natural Thatch & Bamboo",
        "u_value": 0.55,
        "absorptance": 0.45,
        "emissivity": 0.90,
        "cost_tier": "Low / Vernacular",
        "thermal_mass_tier": "Medium-High Insulation",
        "description": "Traditional thick dry thatch with breathable bamboo sub-framing. Superb solar insulation and acoustic dampening."
    },
    "terracotta_tile": {
        "name": "Terracotta Mangalore Clay Tiles",
        "u_value": 1.25,
        "absorptance": 0.65,
        "emissivity": 0.88,
        "cost_tier": "Medium",
        "thermal_mass_tier": "High Thermal Mass",
        "description": "Breathable porous clay tile providing excellent diurnal thermal lag and natural rain dissipation."
    },
    "insulated_puf": {
        "name": "High-Albedo Insulated Sandwich Panels (50mm PUF)",
        "u_value": 0.42,
        "absorptance": 0.25,
        "emissivity": 0.82,
        "cost_tier": "High / Commercial",
        "thermal_mass_tier": "Maximum Thermal Barrier",
        "description": "Commercial reflective white metal skin with rigid polyurethane foam core, reflecting 75%+ solar radiation."
    },
    "adobe_rammed_earth": {
        "name": "Stabilized Adobe & Rammed Earth Walls",
        "u_value": 0.85,
        "absorptance": 0.50,
        "emissivity": 0.90,
        "cost_tier": "Low-Medium / Vernacular",
        "thermal_mass_tier": "Ultra-High Thermal Inertia",
        "description": "Locally sourced earth blocks dampening extreme daytime heat spikes and releasing warmth during cool nights."
    },
    "galvanized_uninsulated": {
        "name": "Corrugated Galvanized Iron (Uninsulated)",
        "u_value": 5.80,
        "absorptance": 0.75,
        "emissivity": 0.25,
        "cost_tier": "Low Initial / High Stress",
        "thermal_mass_tier": "Very Low (Heat Trap)",
        "description": "Uninsulated bare metal sheets causing extreme radiant heat re-radiation onto livestock. Not recommended without thatch underlay."
    }
}

# Species Thresholds & Bioclimatic Constants
SPECIES_PROFILES = {
    "cattle": {
        "name": "Dairy & Beef Cattle (🐄)",
        "optimal_temp_c": (10.0, 24.0),
        "critical_temp_c": 27.0,
        "optimal_humidity": (40, 70),
        "min_clearance_height_m": 3.8,
        "space_per_animal_sqm": 8.5,
        "metabolic_heat_w_per_head": 1000.0,  # ~1000W sensible/latent heat per adult bovine
        "thi_thresholds": {
            "comfort": 68.0,
            "mild_stress": 72.0,
            "moderate_stress": 79.0,
            "severe_stress": 89.0
        },
        "advisory_tips": [
            "Maintain roof ridge chimney clearance (min 400mm width) to evacuate hot buoyant air generated by heavy cattle body heat.",
            "Extend roof eave overhangs at least 1.2m–1.5m to block direct solar radiation from striking resting stalls.",
            "Install grooved non-slip concrete flooring with 1.5% slope toward drainage gutter for rapid manure & moisture clearing.",
            "Orient the long building axis East-West to minimize low-angle solar wall exposure during peak summer afternoons."
        ]
    },
    "goats": {
        "name": "Goats & Sheep / Caprine (🐐)",
        "optimal_temp_c": (12.0, 26.0),
        "critical_temp_c": 30.0,
        "optimal_humidity": (35, 65),
        "min_clearance_height_m": 2.8,
        "space_per_animal_sqm": 2.2,
        "metabolic_heat_w_per_head": 180.0,
        "thi_thresholds": {
            "comfort": 65.0,
            "mild_stress": 70.0,
            "moderate_stress": 76.0,
            "severe_stress": 84.0
        },
        "advisory_tips": [
            "Construct elevated slatted flooring (0.4m–0.6m above ground level) using treated timber or bamboo slats with 15mm gaps for automatic dung/urine drop.",
            "Goats are highly vulnerable to pneumonia from damp cold drafts: maintain adjustable side canvas/baffles for chilly nights.",
            "Ensure dry sub-floor airflow to prevent foot-rot (pododermatitis) and coccidiosis parasites.",
            "Provide raised fodder racks to prevent feed trampling and fungal contamination."
        ]
    },
    "poultry": {
        "name": "Poultry Broilers & Layers (🐓)",
        "optimal_temp_c": (18.0, 25.0),
        "critical_temp_c": 30.0,
        "optimal_humidity": (45, 70),
        "min_clearance_height_m": 2.6,
        "space_per_animal_sqm": 0.15,
        "metabolic_heat_w_per_head": 12.5,
        "thi_thresholds": {
            "comfort": 70.0,
            "mild_stress": 75.0,
            "moderate_stress": 81.0,
            "severe_stress": 88.0
        },
        "advisory_tips": [
            "Chickens lack sweat glands and rely entirely on panting; keep air velocity across bird level between 1.5–2.2 m/s.",
            "Apply high-reflectance white cool-roof paint (albedo > 0.75) or wet thatch sprinkler over corrugated sheets to suppress radiant roof heat.",
            "Maintain continuous ammonia scavenging with minimum 6–10 ACH (Air Changes per Hour) cross-draft ventilation.",
            "Implement evaporative cooling pads on the windward side during dry-heat periods (>35°C, RH < 50%)."
        ]
    }
}


def calculate_thi(temp_c: float, relative_humidity_pct: float) -> float:
    """
    Computes standard NRC Temperature-Humidity Index (THI) for livestock.
    Formula: THI = (1.8 * T_c + 32) - (0.55 - 0.0055 * RH) * (1.8 * T_c - 26)
    Or bioclimatic formula: THI = 0.8 * T_c + (RH/100) * (T_c - 14.4) + 46.4
    """
    return 0.8 * temp_c + (relative_humidity_pct / 100.0) * (temp_c - 14.4) + 46.4


def get_thi_status(species: str, thi_val: float) -> Dict[str, Any]:
    thresholds = SPECIES_PROFILES.get(species, SPECIES_PROFILES["cattle"])["thi_thresholds"]
    if thi_val < thresholds["mild_stress"]:
        return {
            "level": "Comfort (Optimal)",
            "status_code": "COMFORT",
            "color": "#10B981",  # Emerald
            "risk_description": "Normal metabolic activity, zero heat distress. Optimal lactation / weight gain / egg production."
        }
    elif thi_val < thresholds["moderate_stress"]:
        return {
            "level": "Mild Heat Stress",
            "status_code": "MILD",
            "color": "#F59E0B",  # Amber
            "risk_description": "Elevated respiration rate, slight drop in dry matter feed intake (-5% to -10%)."
        }
    elif thi_val < thresholds["severe_stress"]:
        return {
            "level": "Moderate Heat Stress",
            "status_code": "MODERATE",
            "color": "#F97316",  # Orange
            "risk_description": "Heavy panting, noticeable yield suppression (-15% to -25%), increased water consumption."
        }
    else:
        return {
            "level": "Severe / Emergency Heat Stress",
            "status_code": "SEVERE",
            "color": "#EF4444",  # Red
            "risk_description": "Critical danger of thermal collapse / mortality. Urgent misting, evaporative fans, and night cooling required."
        }


def simulate_shelter(
    species: str = "cattle",
    climate_zone: str = "hot_dry",
    ambient_temp_c: float = 38.0,
    ambient_rh_pct: float = 40.0,
    solar_radiation_w_sqm: float = 850.0,
    wind_speed_mps: float = 2.5,
    roof_material_key: str = "terracotta_tile",
    overhang_depth_m: float = 1.2,
    ridge_vent_openness_pct: float = 75.0,
    wall_openness_pct: float = 50.0,
    animal_head_count: int = 10,
    floor_area_sqm: float = 120.0,
    ceiling_height_m: float = 3.8
) -> Dict[str, Any]:
    """
    Simulates thermal physics, ventilation rates, solar ingress, and livestock comfort.
    """
    species_key = species.lower()
    if species_key not in SPECIES_PROFILES:
        species_key = "cattle"
    spec = SPECIES_PROFILES[species_key]

    mat_key = roof_material_key if roof_material_key in MATERIALS_DATABASE else "terracotta_tile"
    mat = MATERIALS_DATABASE[mat_key]

    # Baseline calculations
    base_thi = calculate_thi(ambient_temp_c, ambient_rh_pct)

    # 1. Solar Radiation Heat Ingress
    # Sol-air calculation: T_sol_air = T_amb + (alpha * I / h_o)
    h_out = 15.0 + 3.5 * wind_speed_mps  # Convective heat transfer coefficient W/m²K
    sol_air_temp = ambient_temp_c + (mat["absorptance"] * solar_radiation_w_sqm) / h_out

    # Shading factor from eave overhang
    # e.g., 1.5m overhang cuts direct wall/window solar ingress by ~40-60%
    shading_reduction_factor = min(0.65, 0.20 + (overhang_depth_m / 2.0) * 0.45)

    # Roof heat flux (W/m²)
    roof_heat_flux_w_sqm = mat["u_value"] * (sol_air_temp - ambient_temp_c)

    # 2. Ventilation Rates (ACH)
    # Natural cross-draft airflow through wall openings
    wall_area_eff = (floor_area_sqm ** 0.5) * ceiling_height_m * (wall_openness_pct / 100.0) * 0.6
    q_wind_m3_s = 0.55 * wall_area_eff * wind_speed_mps * 0.65  # Windward capture

    # Stack effect / Chimney thermal buoyancy through ridge vent
    delta_t_est = max(1.0, sol_air_temp - ambient_temp_c)
    ridge_area_eff = (floor_area_sqm ** 0.5) * 0.5 * (ridge_vent_openness_pct / 100.0)
    q_stack_m3_s = 0.6 * ridge_area_eff * math.sqrt(2.0 * 9.81 * (ceiling_height_m * 0.6) * (delta_t_est / (ambient_temp_c + 273.15)))

    total_vent_flow_m3_s = math.sqrt(q_wind_m3_s ** 2 + q_stack_m3_s ** 2)
    shelter_volume_m3 = floor_area_sqm * ceiling_height_m
    ach = (total_vent_flow_m3_s * 3600.0) / shelter_volume_m3

    # Air velocity at animal breathing zone (m/s)
    air_vel_animal_mps = min(3.5, max(0.2, (total_vent_flow_m3_s / (floor_area_sqm ** 0.5 * 1.5))))

    # 3. Interior Temperature Simulation
    # Total internal heat load = Metabolic animal heat + Solar transmission - Ventilative evacuation
    metabolic_total_w = animal_head_count * spec["metabolic_heat_w_per_head"]
    solar_load_w = (roof_heat_flux_w_sqm * floor_area_sqm * (1.0 - shading_reduction_factor))
    net_heat_load_w = metabolic_total_w + solar_load_w

    # Heat evacuated by ventilation: Q = m_dot * Cp * delta_T = (rho * V_flow) * Cp * (T_in - T_amb)
    rho_air = 1.18  # kg/m3
    cp_air = 1005.0  # J/kg.K
    denom = rho_air * total_vent_flow_m3_s * cp_air
    if denom > 0:
        indoor_temp_delta = net_heat_load_w / (denom + (mat["u_value"] * floor_area_sqm))
    else:
        indoor_temp_delta = 5.0

    # Indoor temperature with shading & material damping
    # In well-ventilated shade, interior temp is significantly cooler than sol-air peak and uninsulated sheds
    indoor_temp_c = ambient_temp_c + indoor_temp_delta - (2.5 if mat_key in ["thatch_bamboo", "insulated_puf"] else 0.5)
    indoor_temp_c = max(ambient_temp_c - 4.5, indoor_temp_c)  # Physical limit for passive shading

    # Calculate indoor THI
    indoor_thi = calculate_thi(indoor_temp_c, ambient_rh_pct)
    thi_status = get_thi_status(species_key, indoor_thi)

    # 4. Productivity & Yield Protection Calculation
    if species_key == "cattle":
        # Dairy cattle lose ~1.5 - 3.5 L milk per day above THI 72
        if indoor_thi > 72:
            milk_loss_liters_per_day = min(5.0, (indoor_thi - 72) * 0.35)
        else:
            milk_loss_liters_per_day = 0.0
        yield_protection_summary = f"+{max(0.2, round(4.5 - milk_loss_liters_per_day, 1))} L / cow / day"
        yield_metric_title = "Milk Yield Preserved"
    elif species_key == "goats":
        # Weight gain and disease risk index
        risk_reduction = min(92, max(30, int((ach / 15.0) * 50 + (1.0 if mat_key != "galvanized_uninsulated" else 0.4) * 35)))
        yield_protection_summary = f"{risk_reduction}% Risk Reduction"
        yield_metric_title = "Foot Rot & Pneumonia Shield"
    else:  # poultry
        # Egg lay rate preservation / mortality drop
        egg_protection_pct = min(98, max(45, int(100 - max(0, indoor_thi - 75) * 4.5)))
        yield_protection_summary = f"{egg_protection_pct}% Egg Production"
        yield_metric_title = "Laying Rate Preserved"

    # Solar heat ingress reduction vs uninsulated reference
    uninsulated_solar_load = (MATERIALS_DATABASE["galvanized_uninsulated"]["u_value"] * 15.0)
    current_solar_load = mat["u_value"] * (sol_air_temp - ambient_temp_c) * (1.0 - shading_reduction_factor)
    solar_reduction_pct = min(95.0, max(15.0, ((uninsulated_solar_load - current_solar_load) / uninsulated_solar_load) * 100.0))

    return {
        "status": "success",
        "species": species_key,
        "species_meta": spec,
        "climate_zone": climate_zone,
        "input_parameters": {
            "ambient_temp_c": ambient_temp_c,
            "ambient_rh_pct": ambient_rh_pct,
            "solar_radiation_w_sqm": solar_radiation_w_sqm,
            "wind_speed_mps": wind_speed_mps,
            "roof_material": mat,
            "overhang_depth_m": overhang_depth_m,
            "ridge_vent_openness_pct": ridge_vent_openness_pct,
            "wall_openness_pct": wall_openness_pct,
            "animal_head_count": animal_head_count,
            "floor_area_sqm": floor_area_sqm,
            "ceiling_height_m": ceiling_height_m
        },
        "simulation_results": {
            "ambient_thi": round(base_thi, 1),
            "indoor_thi": round(indoor_thi, 1),
            "thi_delta": round(indoor_thi - base_thi, 1),
            "thi_status": thi_status,
            "indoor_temp_c": round(indoor_temp_c, 1),
            "temp_delta_c": round(indoor_temp_c - ambient_temp_c, 1),
            "sol_air_temp_c": round(sol_air_temp, 1),
            "air_changes_per_hour_ach": round(ach, 1),
            "animal_level_air_velocity_mps": round(air_vel_animal_mps, 2),
            "solar_heat_reduction_pct": round(solar_reduction_pct, 1),
            "roof_heat_flux_w_sqm": round(roof_heat_flux_w_sqm, 1),
            "yield_metric_title": yield_metric_title,
            "yield_protection_summary": yield_protection_summary,
            "cooling_efficacy_tier": "High Bioclimatic Efficiency" if indoor_thi < 74 else ("Moderate Protection" if indoor_thi < 80 else "Supplemental Misting Recommended")
        },
        "boq_materials": [
            {"item": "Roofing Framework", "specification": f"{mat['name']} on treated bamboo / mild steel truss", "qty": f"{round(floor_area_sqm * 1.25)} m²"},
            {"item": "Ridge Chimney Louvers", "specification": f"{round(ridge_vent_openness_pct)}% openable continuous ridge cap", "qty": f"{round(floor_area_sqm ** 0.5, 1)} linear m"},
            {"item": "Overhang Extended Eaves", "specification": f"{overhang_depth_m}m shade projection with storm brackets", "qty": f"{round(floor_area_sqm ** 0.5 * 2, 1)} m"},
            {"item": "Drainage & Floor System", "specification": "Slatted timber/bamboo floor" if species_key == "goats" else "Grooved anti-slip concrete with dung gutter", "qty": f"{floor_area_sqm} m²"}
        ],
        "advisory_notes": spec["advisory_tips"]
    }


if __name__ == "__main__":
    # Quick self-test
    for sp in ["cattle", "goats", "poultry"]:
        res = simulate_shelter(species=sp, climate_zone="hot_dry", ambient_temp_c=40.0, ambient_rh_pct=35.0)
        print(f"=== {sp.upper()} ===")
        print(f"Indoor Temp: {res['simulation_results']['indoor_temp_c']}°C (Amb: 40°C)")
        print(f"Indoor THI: {res['simulation_results']['indoor_thi']} ({res['simulation_results']['thi_status']['level']})")
        print(f"Ventilation: {res['simulation_results']['air_changes_per_hour_ach']} ACH | {res['simulation_results']['yield_metric_title']}: {res['simulation_results']['yield_protection_summary']}")
