"""
Fetch NASA POWER monthly climatology (2001-2020) for the ThermaBuild site presets
and write it to demo/data/climate.js so the browser engine works offline.

Run once while online:  python3 scripts/fetch_nasa_power.py

Temperatures come from the MERRA-2 grid cell, whose mean elevation can sit
hundreds of metres above or below the town (the Leh cell is ~4,530 m, Leh is
~3,500 m). We shift them to the site elevation with the standard environmental
lapse rate, 6.5 K per km, and record both elevations in the output.
"""
import json
import os
import sys
import urllib.request

SITES = {
    # key: (name, lat, lon, site elevation m)
    "leh": ("Leh, Ladakh", 34.1526, 77.5771, 3500),
    "nubra": ("Diskit, Nubra Valley", 34.5428, 77.5619, 3144),
    "kargil": ("Kargil, Suru Valley", 34.5539, 76.1349, 2676),
    "dras": ("Dras, Ladakh", 34.4294, 75.7533, 3280),
    "pangong": ("Pangong Tso, Changthang", 33.7595, 78.6674, 4250),
    "spiti": ("Kaza, Spiti Valley", 32.2276, 78.0710, 3650),
    "new_delhi": ("New Delhi", 28.6139, 77.2090, 216),
    "chennai": ("Chennai", 13.0827, 80.2707, 6),
    "jaisalmer": ("Jaisalmer", 26.9157, 70.9083, 225),
    "bengaluru": ("Bengaluru", 12.9716, 77.5946, 920),
}
PARAMS = "T2M,T2M_RANGE,ALLSKY_SFC_SW_DWN,CLRSKY_SFC_SW_DWN,RH2M,WS2M"
MONTHS = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"]
LAPSE = 0.0065  # K per m
URL = "https://power.larc.nasa.gov/api/temporal/climatology/point?parameters={p}&community=RE&longitude={lon}&latitude={lat}&format=JSON"


def fetch(lat, lon):
    with urllib.request.urlopen(URL.format(p=PARAMS, lat=lat, lon=lon), timeout=60) as r:
        return json.load(r)


def main():
    out = {"source": "NASA POWER climatology API v2 (MERRA-2 / CERES, 2001-2020 monthly means)",
           "lapse_rate_K_per_km": LAPSE * 1000, "sites": {}}
    for key, (name, lat, lon, elev) in SITES.items():
        d = fetch(lat, lon)
        p = d["properties"]["parameter"]
        grid_elev = d["geometry"]["coordinates"][2]
        dt = (grid_elev - elev) * LAPSE  # site is warmer when it sits below the grid cell
        m = lambda k: [round(p[k][mo], 2) for mo in MONTHS]
        t_mean = [round(t + dt, 2) for t in m("T2M")]
        rng = m("T2M_RANGE")
        out["sites"][key] = {
            "name": name, "lat": lat, "lon": lon, "elev_m": elev, "grid_elev_m": round(grid_elev, 1),
            "t_mean": t_mean,
            "t_max": [round(t + r / 2, 2) for t, r in zip(t_mean, rng)],
            "t_min": [round(t - r / 2, 2) for t, r in zip(t_mean, rng)],
            "ghi_kwh": m("ALLSKY_SFC_SW_DWN"),         # all-sky daily global horizontal, kWh/m2/day
            "ghi_clear_kwh": m("CLRSKY_SFC_SW_DWN"),   # clear-sky daily global horizontal
            "rh": m("RH2M"),
            "wind": m("WS2M"),
        }
        print(f"{key:10s} grid {grid_elev:6.0f} m -> site {elev:5d} m  (+{dt:4.1f} K)  Jan {t_mean[0]:6.1f} C  "
              f"min {out['sites'][key]['t_min'][0]:6.1f}  GHI {out['sites'][key]['ghi_kwh'][0]:.2f}")
    here = os.path.dirname(os.path.abspath(__file__))
    dest = os.path.join(here, "..", "demo", "data")
    os.makedirs(dest, exist_ok=True)
    with open(os.path.join(dest, "climate.json"), "w") as f:
        json.dump(out, f, indent=1)
    with open(os.path.join(dest, "climate.js"), "w") as f:
        f.write("// Generated by scripts/fetch_nasa_power.py. Do not edit by hand.\n")
        f.write("(function (g) { g.TB_CLIMATE = " + json.dumps(out) + "; })(typeof globalThis !== 'undefined' ? globalThis : this);\n")
    print("wrote demo/data/climate.js")


if __name__ == "__main__":
    sys.exit(main())
