#!/usr/bin/env python3
"""
Parametric FreeCAD 3D CAD & STEP Solid Builder for Plan 1: 2 BHK Compact Villa (1,158 sq.ft)
Auto-generated by ThermaBuild BIM Engine.
"""

import sys
import os

try:
    import FreeCAD as App
    import Part
except ImportError:
    print("FreeCAD Python API not found. To build solid STEP CAD model:")
    print("Run: FreeCADCmd generate_cad.py")
    sys.exit(0)

doc = App.newDocument("ThermaBuild_plan_1")

# 1. Foundation Slab (Reinforced Concrete Plinth)
slab = Part.makeBox(10860.0, 11090.0, 150)
slab.translate(App.Vector(-300, -300, 0))
slab_obj = doc.addObject("Part::Feature", "Foundation_Slab")
slab_obj.Shape = slab

# 2. Roof Slab (High-Thermal Insulation Overdeck)
roof = Part.makeBox(11060.0, 11290.0, 150)
roof.translate(App.Vector(-400, -400, 3000.0))
roof_obj = doc.addObject("Part::Feature", "Roof_Slab")
roof_obj.Shape = roof

# 3. Exterior Envelope Perimeter Walls
w_s = Part.makeBox(10260.0, 200.0, 2850.0)
w_s.translate(App.Vector(0, 0, 150))
doc.addObject("Part::Feature", "Wall_South").Shape = w_s

w_n = Part.makeBox(10260.0, 200.0, 2850.0)
w_n.translate(App.Vector(0, 10290.0, 150))
doc.addObject("Part::Feature", "Wall_North").Shape = w_n

w_w = Part.makeBox(200.0, 10090.0, 2850.0)
w_w.translate(App.Vector(0, 200.0, 150))
doc.addObject("Part::Feature", "Wall_West").Shape = w_w

w_e = Part.makeBox(200.0, 10090.0, 2850.0)
w_e.translate(App.Vector(10060.0, 200.0, 150))
doc.addObject("Part::Feature", "Wall_East").Shape = w_e

# 4. Interior Room Zones & Partitions

# Room 1: Sit-Out & Foyer (3.12m x 1.38m)
r_box = Part.makeBox(3120.0, 1380.0, 30)
r_box.translate(App.Vector(3400.0, 200.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_1_Sit-Out_and_Foyer")
r_obj.Shape = r_box

# Room 2: Living / Hall (5.28m x 3.72m)
r_box = Part.makeBox(5280.0, 3720.0, 30)
r_box.translate(App.Vector(2200.0, 1700.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_2_Living_/_Hall")
r_obj.Shape = r_box

# Room 3: Dining Room (3.12m x 4.44m)
r_box = Part.makeBox(3120.0, 4440.0, 30)
r_box.translate(App.Vector(3400.0, 5500.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_3_Dining_Room")
r_obj.Shape = r_box

# Room 4: Kitchen (3.24m x 2.4m)
r_box = Part.makeBox(3240.0, 2400.0, 30)
r_box.translate(App.Vector(6600.0, 7500.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_4_Kitchen")
r_obj.Shape = r_box

# Room 5: Store Room (1.2m x 1.8m)
r_box = Part.makeBox(1200.0, 1800.0, 30)
r_box.translate(App.Vector(7600.0, 5500.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_5_Store_Room")
r_obj.Shape = r_box

# Room 6: Bedroom 1 (2.94m x 2.94m)
r_box = Part.makeBox(2940.0, 2940.0, 30)
r_box.translate(App.Vector(300.0, 7000.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_6_Bedroom_1")
r_obj.Shape = r_box

# Room 7: Master Bedroom (2.94m x 4.38m)
r_box = Part.makeBox(2940.0, 4380.0, 30)
r_box.translate(App.Vector(300.0, 2500.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_7_Master_Bedroom")
r_obj.Shape = r_box

# Room 8: Bath & WC (1.92m x 1.38m)
r_box = Part.makeBox(1920.0, 1380.0, 30)
r_box.translate(App.Vector(300.0, 900.0, 150))
r_obj = doc.addObject("Part::Feature", "Floor_8_Bath_and_WC")
r_obj.Shape = r_box


doc.recompute()
step_path = os.path.join(os.path.dirname(__file__), "house.step")
Part.export([slab_obj, roof_obj], step_path)
print(f"Exported parametric solid CAD STEP: {step_path}")

fcstd_path = os.path.join(os.path.dirname(__file__), "house.FCStd")
doc.saveAs(fcstd_path)
print(f"Saved native FreeCAD project: {fcstd_path}")
